In [66]:
import array

In [96]:
a = array.array('B',[1,2,3]) 

In [69]:
a

array('B', [1, 2, 3])

In [73]:
type(a[0])

int

In [8]:
b = array.array('B', [1,2,3])

In [9]:
a + b  # 오퍼레이터 오버로딩

array('B', [1, 2, 3, 1, 2, 3])

In [10]:
class A:
    def __add__(self, x):
        print('add')
        return 0

In [11]:
a = A()

In [12]:
a + 1

add


0

In [113]:
dir(array.array('b',[1,2,3])), dir(np.array([1,2,3]))

(['__add__',
  '__class__',
  '__contains__',
  '__copy__',
  '__deepcopy__',
  '__delattr__',
  '__delitem__',
  '__dir__',
  '__doc__',
  '__eq__',
  '__format__',
  '__ge__',
  '__getattribute__',
  '__getitem__',
  '__getstate__',
  '__gt__',
  '__hash__',
  '__iadd__',
  '__imul__',
  '__init__',
  '__init_subclass__',
  '__iter__',
  '__le__',
  '__len__',
  '__lt__',
  '__module__',
  '__mul__',
  '__ne__',
  '__new__',
  '__reduce__',
  '__reduce_ex__',
  '__repr__',
  '__rmul__',
  '__setattr__',
  '__setitem__',
  '__sizeof__',
  '__str__',
  '__subclasshook__',
  'append',
  'buffer_info',
  'byteswap',
  'count',
  'extend',
  'frombytes',
  'fromfile',
  'fromlist',
  'fromunicode',
  'index',
  'insert',
  'itemsize',
  'pop',
  'remove',
  'reverse',
  'tobytes',
  'tofile',
  'tolist',
  'tounicode',
  'typecode'],
 ['T',
  '__abs__',
  '__add__',
  '__and__',
  '__array__',
  '__array_finalize__',
  '__array_function__',
  '__array_interface__',
  '__array_prepare__',


In [22]:
import numpy as np

In [119]:
a = np.ndarray([1,2,3])
b = np.array([1,2,3])
c = array.array('b',[1,2,3])
a,b,c,type(a), type(b), type(c)



(array([[[0., 0., 0.],
         [0., 0., 0.]]]),
 array([1, 2, 3]),
 array('b', [1, 2, 3]),
 numpy.ndarray,
 numpy.ndarray,
 array.array)

In [146]:
import numpy as np

a = np.array([1,2,2.1])

a,type(a),a.dtype, type(a[0]) # array는 클래스가 아니라, 팩토리 메소드로 인스턴스를 반환하는 함수이다.
# 출력:
# (array([1. , 2. , 2.1]), numpy.ndarray, dtype('float64'), numpy.float64)

(array([1. , 2. , 2.1]), numpy.ndarray, dtype('float64'), numpy.float64)

TypeError: data type '' not understood

In [15]:
type(a) # array는 클래스가 아니라, 팩토리 메소드로 인스턴스를 반환하는 함수이다.

numpy.ndarray

In [82]:
b = np.ndarray([2,2,2])
c = np.array([2,2,2])
b

# array([[[3.7104e-321, 1.7673e-320],
#         [6.5365e-321, 1.4768e-320]],

#        [[1.4768e-320, 6.5365e-321],
#         [1.7673e-320, 3.7104e-321]]])

array([[[3.7104e-321, 1.7673e-320],
        [6.5365e-321, 1.4768e-320]],

       [[1.4768e-320, 6.5365e-321],
        [1.7673e-320, 3.7104e-321]]])

In [87]:
b.shape, b.ndim, b.dtype, b.size, b.data, b.

((2, 2, 2), 3, dtype('float64'), 8, <memory at 0x2acc7c310>)

In [16]:
import seaborn as sns

In [17]:
t = sns.load_dataset('tips')

In [18]:
# __array__가 있으면 NumPy와 연동가능
# __array_warp__

In [94]:
v = array.array(1,2,3)
a = np.array([1,2])
type(a), type(v)

TypeError: array() takes at most 2 arguments (3 given)

In [30]:
a.shape # shape을 꼭 기억 = 인트로 스펙션

(3,)

In [31]:
a.ndim

1

In [32]:
a.dtype # 데이터타입

dtype('int64')

In [34]:
a

array([1, 2, 3])

In [35]:
b = tf.constant([1,1])

NameError: name 'tf' is not defined

In [37]:
import tensorflow as tf

In [38]:
x = tf.keras.datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [39]:
x

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [100]:
x.shape, \   # 배열의 모양
x.ndim, \    # 배열의 차원
x.data, \    # 배열이 저장된 메모리주소. 이 주소부터 데이터가 연속적으로 저장되어 있음
x.size, \    # 배열 요소의 갯수 (배열안의 배열 갯수 아님, 그냥 배열안의 요소 하나하나를 의미!)
x.dtype      # 배열 요소 하나의 데이터 타입
x.itemsize, \# 배열 요소 하나의 사이즈


((60000, 28, 28), 3, 47040000, <memory at 0x2accb9300>, 1, dtype('uint8'))

In [40]:
len(x)

2

In [43]:
x, y = tf.keras.datasets.mnist.load_data()

In [45]:
len(x), len(y)

(2, 2)

In [47]:
(x,z), (y,u) = tf.keras.datasets.mnist.load_data()

In [48]:
x.shape  #[ 갯수 == 차원 # shape,ndim => 차원 # dtype => 타입

(60000, 28, 28)

In [49]:
x.dtype 

dtype('uint8')

In [52]:
# 여기서 부터 디스크립터 등장
x.shape

(60000, 28, 28)

In [53]:
tips = sns.load_dataset('tips')
tips.total_bill

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [54]:
tips.size # 원소의 갯수다. 
          # 분석은 책 많이 읽어야 한다.

1708

In [55]:
# introspection

In [56]:
a.itemsize  # 알면좋다.

8

In [57]:
a.data  # 넘파이에서는 일렬도 저장한다. 차원 상관없이. 외우자. 
        # 스트라이드(아주아주 멋진 개념), 스트라이드 트리 - 배열에서 어떤 값을 빨리 뽑는지..영상처리에서 배운다

In [58]:
# .에 관련된것은 디스크립터를 배우면 이해가 높아진다.

In [ ]:
# 꼼수
# 매틀랩을 배운 사람: 
# 데이터 분석은 대부분 2차원이다. (시계열 데이터 예외)
# 인공지능은 3차원 데이터 이상 (공간개념) 
    # 지도를 움직이는 사람과 => 공간지능이 부족 => matlab 세상의 모든 것을 2차원으로 생각할 수 있다.
        # (60000, 28 ,28) => (60000, 28) (28)
        # 2차원 관점에서 32차원 이해하기
    # 내가 움직이는 사람 => 축복받은 사람

In [61]:
a = np.arange(24).reshape(2,3,4)

In [62]:
a  # 3*4가 2개있다. 공백! 기준 구별하기

# array([[[ 0,  1,  2,  3],
#         [ 4,  5,  6,  7],
#         [ 8,  9, 10, 11]],

#        [[12, 13, 14, 15],
#         [16, 17, 18, 19],
#         [20, 21, 22, 23]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [63]:
a = np.arange(24).reshape(3,2,4)

In [65]:
a  # 밖에서 부터 [를 제거한다. # 이거 연습하기  # 시계열 데이터는 3차원을 잘 해야한다. 

# array([[[ 0,  1,  2,  3],
#         [ 4,  5,  6,  7]],

#        [[ 8,  9, 10, 11],
#         [12, 13, 14, 15]],

#        [[16, 17, 18, 19],
#         [20, 21, 22, 23]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# 4차원을 -> 1차원, 3차원
# 3차원 -> 1차원, 2차원으로 나눠서 생각한다. 
# 공간감각을 익히지 않으면 진짜 힘들다. 
# 자연어 처리는 차원이 좀 낮다. 영사처리는 인생에 대해 다시 생각해라. 

In [ ]:
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

In [147]:
type(range(10))

range

In [148]:
dir(range)

['__bool__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index',
 'start',
 'step',
 'stop']

In [151]:
for i in range(len(a)):
    print(i,a[i])

[1.  2.  2.1]
0 1.0
[1.  2.  2.1]
1 2.0
[1.  2.  2.1]
2 2.1
