In [28]:
import numpy as np

In [52]:
# 벡터(배열)의 형태 바꾸기

In [53]:
a = np.arange(24)

In [54]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [58]:
b = a.reshape((2,12))

In [59]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [62]:
c = b.copy()

In [63]:
c is b

False

In [70]:
c.resize((6,6), refcheck=False)

In [71]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [72]:
d = c

In [73]:
d is c

True

In [74]:
d.resize((6,6), refcheck=False)

In [75]:
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [76]:
d.resize((10,10), refcheck=True)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [ ]:
# 정리: resize는 독립된 배열의 shape을 변경해준다. 빈곳에는 기본으로 0을 채워준다. 
# 그리고 반환값 없이 자기자긴을 변경하기 때문에 refCheck를 통해 공유되고있는 배열인지 확인하는 기능을 제공한다.

In [79]:
np.resize([1,2,3,4],(6,6))

array([[1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 4]])

In [ ]:
a.resize()

In [80]:
a_2d = np.arange(36).reshape((6,6))

In [81]:
a_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [85]:
b_2d = np.resize(a_2d, (8,8))
b_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27]])

In [84]:
a_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
a.resize( new_shape, refcheck=True )     # 자기자신을 변경 => 그래서 refcheck가 필요하다.
np.resize( ndarray_deepcopy, new_shape ) # deep_copy

In [ ]:
a.reshape( new_shape )
np.reshape( ndarray_deepcopy, new_shape )

In [86]:
a = np.arange(100).reshape((10,10))

In [87]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [93]:
a = a.reshape((2,5,10))

In [94]:
a.shape

(2, 5, 10)

In [96]:
a[:,2,::2]

array([[20, 22, 24, 26, 28],
       [70, 72, 74, 76, 78]])

In [97]:
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [98]:
a[0,:,1]

array([ 1, 11, 21, 31, 41])

In [102]:
a[:,2,-4:]

array([[26, 27, 28, 29],
       [76, 77, 78, 79]])

In [106]:
a = a.reshape(5,4,5)

In [107]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [109]:
a[2:4,...]

array([[[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]]])

In [110]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [111]:
b = a[0]

In [112]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [113]:
b[None]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [117]:
b[:,None]

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19]]])

In [119]:
b[:,:,None]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]]])

In [123]:
animals = np.array( \
    [('Rabbit', 400),('hippo', 1), ('tiger',1),('cow', 100)],\
    dtype=[('animal_name', '<U10'),('count', '<i4')])

In [124]:
animals[0]

('Rabbit', 400)

In [131]:
animals[0],animals['animal_name'], animals['count']

(('Rabbit', 400),
 array(['Rabbit', 'hippo', 'tiger', 'cow'], dtype='<U10'),
 array([400,   1,   1, 100], dtype=int32))

In [132]:
a = np.arange(100).reshape((10,10))

In [133]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [134]:
b = a.flatten()

In [135]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [136]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [137]:
a[0,0] = 100

In [138]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [139]:
a

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [140]:
b[0] = 100

In [141]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

In [142]:
c = np.arange(100).reshape((10,10))
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [144]:
d = c.ravel()

In [146]:
c[0,0] = 100

In [147]:
c

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [148]:
d

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

In [149]:
d[0]= 200

In [150]:
c

array([[200,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [151]:
f = np.ravel(c)

In [153]:
f[0] = 300

In [154]:
c

array([[300,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [ ]:
bigdata = np.arange(1000)

In [155]:
a  = 10

In [156]:
with a

SyntaxError: expected ':' (1871266785.py, line 1)

In [157]:
with a :

SyntaxError: incomplete input (2194699984.py, line 1)

In [158]:
with a:
    pass

TypeError: 'int' object does not support the context manager protocol

In [162]:
class A:
    def __enter__(self):
        print('enter')
    def __exit__(self,a,b,c):
        print('exit')

In [163]:
a = A()

In [165]:
with a:
    print('--------------')
    pass

enter
--------------
exit


In [201]:
a = open('./test.txt')

In [202]:
b = a.buffer.read()

In [203]:
b

b'asdf\nasdf\nasd\nfa\nsdf\nasd\nfa\nsd\nfa\nsd\nfas\ndf'

In [279]:
with open('./test.txt','w',encoding='UTF-8') as f:
    contents = '''
The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
    '''
    f.write(contents)

In [253]:
with open('./test.txt','r',encoding='UTF-8') as f:
    contents = f.read(-1)
    print(contents)


The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
    


In [255]:
import re

# 파일을 열고 내용을 읽은 다음, 'better'를 'butter'로 대체합니다.
with open('./test.txt', 'r+', encoding='UTF-8') as f:
    contents = f.read(-1)
    tokens = contents.split(' ')
    for i in range(len(tokens)):
        if re.match(r'[.+?]?better[.+?]?', tokens[i]):
            tokens[i] = "butter"
    print(tokens)
    updated_contents = ' '.join(tokens)
    
    # 파일 포인터를 시작 위치로 이동합니다.
    f.seek(0)
    # 수정된 내용을 파일에 씁니다.
    f.write(updated_contents)
    # 파일의 나머지 부분을 삭제합니다(수정된 내용이 원래 내용보다 짧을 경우를 대비).
    f.truncate()


['\nThe', 'Zen', 'of', 'Python,', 'by', 'Tim', 'Peters\n\nBeautiful', 'is', 'butter', 'than', 'ugly.\nExplicit', 'is', 'butter', 'than', 'implicit.\nSimple', 'is', 'butter', 'than', 'complex.\nComplex', 'is', 'butter', 'than', 'complicated.\nFlat', 'is', 'butter', 'than', 'nested.\nSparse', 'is', 'butter', 'than', 'dense.\nReadability', 'counts.\nSpecial', 'cases', "aren't", 'special', 'enough', 'to', 'break', 'the', 'rules.\nAlthough', 'practicality', 'beats', 'purity.\nErrors', 'should', 'never', 'pass', 'silently.\nUnless', 'explicitly', 'silenced.\nIn', 'the', 'face', 'of', 'ambiguity,', 'refuse', 'the', 'temptation', 'to', 'guess.\nThere', 'should', 'be', 'one--', 'and', 'preferably', 'only', 'one', '--obvious', 'way', 'to', 'do', 'it.\nAlthough', 'that', 'way', 'may', 'not', 'be', 'obvious', 'at', 'first', 'unless', "you're", 'Dutch.\nNow', 'is', 'butter', 'than', 'never.\nAlthough', 'never', 'is', 'often', 'butter', 'than', '*right*', 'now.\nIf', 'the', 'implementation', 'is', '

In [292]:
with open('./test.txt','r',encoding="utf-8") as f:
    contents = f.read()
    print(contents)


The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
    
The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex

In [269]:
with open('./test.txt','a',encoding="utf-8") as f:
    contents = f.write('\nhey! there is a typo in this sentenses!')
    print(contents)

40


In [291]:
with open('./test.txt','r+',encoding='UTF-8') as f:
    contents = f.readlines()
    contents.pop()
    contents.pop()
    f.write(''.join(contents))

In [293]:
def readfile(filepath='auto.txt'):
    if filepath:
        with open(filepath,'r',encoding='utf-8') as f:
            return f.readlines()

In [295]:
def resetfile(filepath='auto.txt'):
    if filepath:
        with open(filepath,'w',encoding='utf-8') as f:
            return f.truncate()

In [311]:
def rewritefile(filepath='auto.txt', contents=""):
    if filepath:
        with open(filepath,'w',encoding='utf-8') as f:
            return f.write(contents)

In [312]:
def writefile(filepath='auto.txt', contents=""):
    if filepath:
        with open(filepath,'a',encoding='utf-8') as f:
            return f.write(contents)

In [297]:
resetfile('test.txt')

0

In [298]:
readfile('test.txt')

[]

In [307]:
contents = '''
The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
    
The Zen of Python, by Tim Peters
'''
writefile('test.txt',contents=contents)

896

In [308]:
readfile('test.txt')

['\n',
 'The Zen of Python, by Tim Peters\n',
 '\n',
 'Beautiful is better than ugly.\n',
 'Explicit is better than implicit.\n',
 'Simple is better than complex.\n',
 'Complex is better than complicated.\n',
 'Flat is better than nested.\n',
 'Sparse is better than dense.\n',
 'Readability counts.\n',
 "Special cases aren't special enough to break the rules.\n",
 'Although practicality beats purity.\n',
 'Errors should never pass silently.\n',
 'Unless explicitly silenced.\n',
 'In the face of ambiguity, refuse the temptation to guess.\n',
 'There should be one-- and preferably only one --obvious way to do it.\n',
 "Although that way may not be obvious at first unless you're Dutch.\n",
 'Now is better than never.\n',
 'Although never is often better than *right* now.\n',
 "If the implementation is hard to explain, it's a bad idea.\n",
 'If the implementation is easy to explain, it may be a good idea.\n',
 "Namespaces are one honking great idea -- let's do more of those!\n",
 '    \n',

In [314]:
writefile('test.txt','\n Hey there are typos in these sentences!')

41

In [315]:
readfile('test.txt')

['\n',
 'The Zen of Python, by Tim Peters\n',
 '\n',
 'Beautiful is better than ugly.\n',
 'Explicit is better than implicit.\n',
 'Simple is better than complex.\n',
 'Complex is better than complicated.\n',
 'Flat is better than nested.\n',
 'Sparse is better than dense.\n',
 'Readability counts.\n',
 "Special cases aren't special enough to break the rules.\n",
 'Although practicality beats purity.\n',
 'Errors should never pass silently.\n',
 'Unless explicitly silenced.\n',
 'In the face of ambiguity, refuse the temptation to guess.\n',
 'There should be one-- and preferably only one --obvious way to do it.\n',
 "Although that way may not be obvious at first unless you're Dutch.\n",
 'Now is better than never.\n',
 'Although never is often better than *right* now.\n',
 "If the implementation is hard to explain, it's a bad idea.\n",
 'If the implementation is easy to explain, it may be a good idea.\n',
 "Namespaces are one honking great idea -- let's do more of those!\n",
 '    \n',

In [342]:
with open('berry2.jpeg', 'rb+') as f:
    # img = f.read()
    updated_img = re.sub(b'\x04', b'\x03', img)
    print(updated_img)
    f.write(updated_img)

b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00\x84\x00\t\x06\x07\x13\x13\x12\x15\x13\x13\x13\x16\x15\x15\x17\x19\x1b\x1b\x19\x17\x18\x18\x1e\x1d\x1b\x1a\x19\x18\x1d\x1a \x1a\x18\x1f \x1b\x1f( \x1a\x1b&\x1f\x1e\x1a!1!%*+...\x1b!383-7(-.+\x01\n\n\n\x0e\r\x0e\x1b\x10\x10\x1b/% %///-/--////2--/-----/.----.----/-/--/------------/\xff\xc0\x00\x11\x08\x00\xe1\x00\xe1\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1c\x00\x00\x02\x02\x03\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x05\x03\x06\x00\x02\x07\x01\x08\xff\xc4\x00G\x10\x00\x01\x02\x03\x03\x05\x06\x03\x03\x08\x05\x02\x06\x03\x00\x00\x01\x02\x11\x00\x03!1\x03\x12A\x05"Qaq\x06\x132\x81\x91\xa1B\xb1\xf0R\xc1\xd1\xe1\x14\x15#3br\x92\xf1\x074s\xb2\xc2\x16\xd25\x82\xa2\xb3\xc3\xe2\x17CS\xff\xc4\x00\x1b\x01\x00\x02\x03\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x03\x02\x05\x06\x01\x00\x07\xff\xc4\x00=\x11\x00\x01\x02\x03\x03\x06\x03\x05\x02\x05\x02\x07\x01\x00\x00\x00\x01\x02\x11\x00

In [ ]:
b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00\x84\x00\t\x06\x07\x13\x13\x12\x15\x13\x13\x13\x16\x15\x15\x17\x19\x1b\x1b\x19\x17\x18\x18\x1e\x1d\x1b\x1a\x19\x18\x1d\x1a \x1a\x18\x1f \x1b\x1f( \x1a\x1b&\x1f\x1e\x1a!1!%*+...\x1b!383-7(-.+\x01\n\n\n\x0e\r\x0e\x1b\x10\x10\x1b/% %///-/--////2--/-----/.----.----/-/--/------------/\xff\xc0\x00\x11\x08\x00\xe1\x00\xe1\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1c\x00\x00\x02\x02\x03\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x05\x03\x06\x00\x02\x07\x01\x08\xff\xc4\x00G\x10\x00\x01\x02\x04\x03\x05\x06\x03\x04\x08\x05\x02\x06\x03\x00\x00\x01\x02\x11\x00\x03!1\x04\x12A\x05"Qaq\x06\x132\x81\x91\xa1B\xb1\xf0R\xc1\xd1\xe1\x14\x15#3br\x92\xf1\x074s\xb2\xc2\x16\xd25\x82\xa2\xb3\xc3\xe2\x17CS\xff\xc4\x00\x1b\x01\x00\x02\x03\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x04\x02\x05\x06\x01\x00\x07\xff\xc4\x00=\x11\x00\x01\x02\x04\x03\x06\x04\x05\x02\x05\x02\x07\x01\x00\x00\x00\x01\x02\x11\x00\x03!1\x04AQ\x12aq\x81\xa1\xf0"\x91\xb1\xc1\x05\x132\xd1\xe1\x14\xf13Rr\x82\xb2B\x92\x15#Ss\xc2\xd2\xe24\xff\xda\x00\x0c\x03\x01\x00\x02\x11\x03\x11\x00?\x00\xadL\x90R\xa2Uj\xee\x9eP\x9b\x19?2\x80\x14\x07H\xb0\xe2\xe6*l\xe0\xa5\xa8\xa9O\xc5\xeau\x8a\xfc\xfc:\xb3\xadI\xf0\xa5J\x0f\xc9\xccS\xe1\xc8c\x1a\x1f\x8d\x05\x99\x88\x19W\xcc\x1f\xcf\xe0Z\x05\x95\xfb;\x86\x83\xce\x1aZ\xe5)O\xbe\x03\xf1\xb4/\xda\x19\x88I\xa1I\xd7\x9b\xd8\xf3\x88\xd3\x84R\x16\xa4\xac1B\x88n\'O#~\x90\xd8\x14\xdax\xa2\xda\xd9\xac\x11\xb3\xda\xe5\xfc\xaf\xca\r\xc4JFP\xe6\xb6\xe1k\xc2\xf9SC\x84\xdc\x03\x05\xe2\xca\x81\xadR\x00\xa7\x0c\xc3\x8d\xf8\xfaG\x89/H\xd0\xcb\x99)iJJo\\\xad\xafXa\xb1\xd4S\x94 \xb9\x05\x9f\x83\xc5\x93bb&*vM\xd7\xf1\xa9Y\x01%$\xd1 )\xc2uv\x0ek\xc6*\xbd\x98\xc4\x135J[eB]\x9b\x85\xbd\xe2Um\xc5I\xc4\xaad\xa6|\xb9A:q\x85\x94\x85\x15\x92\xf09\xd8\xd9\x8aZp\xb8p(\x92\x0b\xef\xb7\x90b7\x97\x8e\xaf=I\x96\x9c\xcbP\x00\x03RG\x99\x8a\x86\xdb\xc6\x95\xccJB\x19\x13f\tI\x98\xa6\x1e\x16\xccBN\xf1b\xa1v\x15\xeb\x03\xablL2L\xe9\x853\x00l\x8e\x9b\xcd\xa6P\x03\xb3!\x89/Z\xf3\x0c\x9fbc\n\xe7K&b\x86@\xa7Z\x89P9\xbcuQ,\xe35\xaeT-\x1dD\xb0\x1dF\x12N\x08\xa2rd\xaa\xaa5-V\x15\xdcI\'=7\xc5\xfaF\xcd\\\xb9iJX\xe5\x14}>\x80\x16\x8a\xb6\xde\xc6!R\xa7\xcaRZt\xbaf\x1a\x94\x97o\xe9\xfb\xe2\xe9\xb1\xf1\xa2t\xac\xc97\xcao\xc8\xe9\xca\xbe\xb1\xcb1\xd3\x8a\xb1\xb3\x8b\xf8\xd6\xb1W\xae\xf1\x1e\xcd\x03\x95,;\xc2\xb2\xa4\xa9A`\xdd \x9f+\xfa\x18\xdbh\xec\xd0p\xe9\x9b)\x89Bs)H5\xcan\x0fK\xf9\x18A\'hL\x04$\xadLK\x1a\xdd\xfa\xc5\xb7\xb2;FRGu1\x92Ul\xc2\x8a\x06\x9a\xdc\x1f\xc6*\x1b\x7f\x07\xdc\xe2W)$\x10\x92\xe0\x8e\x17\x03\xa8\xb7\x949,9)0\xc2&\x84\xa4\x85\xa6\xd5\x1b\xc1\x8e\x95\xb3\x10;\xa0e(\xf7\x88\x0b%\xc8\x1b\xac-W*ri\xa8\x89U\x88\x98\xecR\xc5\x82M\x18\xd0\x8ar\xb4W\xb6\x16<\x19A\xceR\xc6\xa0;\xb9\xf0\x9a\xd0^\xb0\xff\x00\x02][\xeb\xdc$\xe6)e\x1d\xd6#\xd4\x81X\xa5Z\x14\x14Dk\xe5\xad\nK\x8a\xd3\x9fN\xf2\x89\x02A%+^P\x1cPg"\xb4\x01\x8bq\xac-\x9a\x9c\xa4\x8a\x94\xbf\x02\t5\x02\x86\xc6\x18\x04\x02\xe9 \x95|5\x01 \x11\x98iRts\x1aN\x94\xbf\xdeMB\x8c\xb52\x9c\xa4\xfe\xd0\x83\xe1\xcfqBK\x83p:\xc7\x91^\xcf_\xc0\xaf\x94\x18\x16\xef\xd1\xb9\xde\x94\xe2a<\x92\x94.gx\x9c\xee\tAJ\x9b*\xb46\xe0\xe1\xbeP\x8er\x9d*.\x00\xcdQ\xa9\xd5\xf9\xd3\x8c\x1b\xb4\xe6\x0e\xf0\xb3\x94\xa7\x89\xf4\x1c\xe1\x1c\xe9\x8eO#\xe4?\x08zR^\x01=A7\xee\x9d/\xcf\x8dc\xd5*\x95\xa0\xcd\x03*\xe1\x8f\xf7\x8d\xa6L\xd2\xe6!\xc2\xab~\x95\x03\xe9\xa1\xb0(LT\xa9[K\t\xd6-\x9b?\x036t\x92\x10\xca(J\x95\x95\xeb\x95$;q5\x05\xba\xc2\x99\x12T\xb9\x8c\x01\x96\r\xee\xc0y\xe9\x16\tS\x0c\xb9aR\xe6\xe7,B\x90\x06U 3\x17\x05\x83\xb3\x81rZ \xc1\xcc\xcd\xbc\x90YJl\xa6\xea\x03\xa5\xbd\xe1b\xa2\x84\xed4EX\x193q;NA5mkZ\xb6\xb4-\xef\r\xa4\xd1%M\x9d\tf\x7fz8$~1\xeae($\xce\xc9\x9a]S\x98\xe8\xa5\x02\xd4\x06\x84_\xcb\xca7\xc1\xcbAB\xf3:U\x982~\x10\x0f"c\xcc>\x06l\xc4-IH\xc8\x0b\x12H\x01\xc6\x80\x92\xc5M\xa0&\x87\xce\x14\n&\xd1t\xc0;\xd3\xa5\xfa=\xed\xc1\xa9P\xe5J*\xb9\xcat\xa5O\x005\xfa1\xa6?\x12\xa9\x8aR\x8f\x88\xdf\x99\xd4\xd2\x97\xf9\xc4\x98\x89\xea,\x14\xe4$qv\x0eKr\x15\xf7\x88\xf3\x04\x94\xac:T\x18\x8f-A\xe2\x08\xe1\x12\x06\'\xb2\xd5m~\xfdXd \x1c\xcb\xe0\xa8\xc8;\xf5\x94\xff\x00\xb5\xf3\x8c\x8fs\xef\xce$\xc7w\x7f\xdb\x12\xca\xc2\x99s\x00S\x8a\xba\x8f:_\x94,\xdbbZC&\x80\xa8\xa9\xdd\xc9I\xa8\xe9\xd3\xf1\x86\xfb{\x1b)Ey&)@\x1b\xae\x97\xb9\xa3\x87\xf3\xfc"\x99\x8aJ\xa7\xa9\x91@nM\x80\xe1\xe7\xc2\x0b!\x05\xebmb\x9f\x1c\x01\x00\x80J\xaa\x00\x17\xa8\xa8\x1e\xf9\x8a\xd9\x8cK\xb2\xa79\x00\x87D\xc0O\xf2\xa8\x12>C\xdcC,b\x84\xc0%\xceI\xcc\x90\x02&\xa6\xe4=\x01\xe3\xc2\xbe\xd1\x92\xb6x\x94S\x98\x164\xd6\x840$\x00\xc7\x83\x8eP\\\xb7\xces\x1c\xc94\n \x15\x1aX\x92\x1cY\xb9W\xacMJ\nV\xd2M;\xec\xeb\x15\x12\xbe\r5~%\x908W\xd2\x9d`\xac?\xf8\x7f;/x\'\xe1T\t\x05\x8a\xc8 k\\\xa4{\xc7\x9b{e\tr\x94\x85\x06R\xacA\x04PP\xb8\xd3\xf11\x10@\x040\x0e\xc6\xe0Z\xaf\xebN\x95\x8cR\x13\xa8\x0e\x18R\x82\xfc8\x96\xd3\x9cIj\xdac\x98\x87U\xf0\xd5\x92\x14\x17QjhA\xf5\x03\xda*\xfb1\x05\x19\xc2\xa8\xfc\r\xd9\xe0\\& \x15\x85\x1a\x97\x17\xa8 i\xccE\xa3\x1a\x99jrR\x0b\x01@\x18Pz\xb5\xa2\xaf\xb4\xb6R\x91\xbe\x8f\t\xf8u\x1a\xd1\xfePd((\x977\x80~\x92n\x1ea\x9cC\xf0\xbbp\x87\xdf\xafU$\x15%\x8c\xc2TPR\xc3\xba+pH\xe7b8r\x82vV5)\xc3\xe4D\xb4\xee\x82\xa5\x92Fe\x92r\xee\x92\x0b\x00\xf6K\x1a\\\xde)\xb2\xb1\x9b\xc1G\x8f\xcb\xef\x86rv\xa2\x8a\x95\x94\x87XP\xa8\x07\xc5V\x0e(y\x865\xe7\x1dT\xb5\x01\xb2 \xb8U\xcbT\xd5\xcfY\xaa\x8d7\x0c\x87\x95_P\x0eU\xbcv3h\x84\x1c\x8bS\x1a\xb2X0K8.\xf7\xe4\xdeqY\x99\x86*Q\x9c\x84\x90\xf9\x8b\x9e$\x92\x0fJ\xbc\x19\xb3\xf0\x05,\xb9\x95Qr\xdc4\xbfO\x9c\x1cA\x0b)qg\xb8\xb0\x0fCg\xe8}\xe1o\x98\xdfL<\xbf\x87\x05\xce\\\xd2H\xda\xc8\x16\xd5\xfc\xe9\xbd\xde\xcf\x15\xc4\xf6}t\xdfb*7u~\xae`\x8cn\xc2T\xc23MJUc\xbat\xe9\r\x80.]\xdc3Q\xdc\xd7Sn\x91\xb1\xc40\t&\xa2\xdcK\xd5\xc9}-H\xef\xce\x99\xd8\x8f+\xe1xu3\xa6\xd6\xa9\xf6\x84\xb8|"\xb0\xd2\xcaG\xed\x14\x1d\xf2\xbf\x958[\xe7\r\xf66)%9\x8a\xd8\x02\xc5-\xbdP\xe4\xb5\x98\x1a^ \xc4\xe27\x92]\x9e\x84&\x84r\x85\x18\xf9*\x05KA\xa8\xa6Vbo_\xe6\x88\xd2a\xf1\xc4\x84\x9f\xd2%F@$i|\x9b76\x16\xf2\x8b\xee\r=\xe2R\x84\xeb0&\xb4*Q!\x81M\xc6W!\xc0\xf9\xc6mi\xb30\xc1RT\xe9*I\x06\xfb\xe9I\xdc,h@),CR+;\x1f\x1a\x8c\x95,@\xe0\xfc-j\xbf\xce\x06\xc6m"\x0ea\xf1=\xeb\xf5\xe7\x00\x12\xcb\xb3s\x7f\xc4<V\x9b\x93J\x1e&\xf7v\xe4\xc7&f\x0c&7\x12\x1b\xe2~gM}\xe1L\xc9\xd7\xbdc\xdcN(\x1a\xfc\xbf=`ID\xada ?\x1e\x9a\xc5\x94\xa9l+\x14\x98\xbchz\x1e\xfe\xf1\xe4\xfcO\x0b\xc3]\x83\x88\x12\xceu\x04,\x10AB\x9f{\xfaj\x93\xa8/q\x03v\x9fe\xf7\x13P\xc5\xf3KB\x89\xfe%%*"\xfa\x05\x01\xe4i\x01K\x9eX\nS\x80\xf9\xc1\x88t\xd2+\xa4O\xda\x98\xea\x8b\x18\x9c\xa5\x15\x90\xf6u9z\x0b\x077hi\xb2\xf1\x15\xceTA\x00\x10y\x83OhE\x82\x9eQ\x90\xa1e3\x02\x8b\x82(\x90\x19\x8dC\x18a\xb3\xf1Y\xc7v\x9f\xb4\x15\xcf\x9cW\xce\x96\xc9x\xd0I\xc5%KJ5\xb5-\xce\xd5\xca,\xd2\x14\xb9\xc5sT\xa0\xf4pH\xcc\xa755\xbf>\xb1&\x0eYY\xee\xc1\x0e\x9a\x8c\xc4%9R\xe5D\xbbX_\x90\x80\xe7O\x0c\x94\x04%3\x00\x01L]\xc8\xb9\xbbW\x85\xb9D\xf3R\x90\x90\xad\xe0\xa2\x0b\x02\x19\x88\xe0~!\xe9v\xe6R;\xf9\xc5\x88\xa8\xa54\xb7\xdd\xab\\\xf8\xef\x9dx B\xd9iQB\x9c\xa5/T\xd7y\x0f\xe2\x02\xbc\xf5\xb5b,T\x94M#|%K\x98A9r!)\xa3,\xe5\x14s\x980\x14\xcb\x1b\xe2\n\x14\x91\x90\xd4\xd7+2PK\xee\xe6Qrm\xcb\xacI\xb4\xa7I\x98;\xd4\xadR\xe6\x90s\xcaP\xcc\x8c\xea\xa2\x94\x95s\xa1\xa8\xa7\x1bD\xd3N\xfb\xcb\x9f\xa4w\xc4\xe2\xfe^OBkR\xe2\x94\xa9/\x0b?AW\xf0z\xff\x00\xf6\x8c\x87\xbf\xf4v?\xec\x0f\xea\x1f\x8cd\x1b\xf4\xea\xfeS\xd6\x15\xf9\xf8\x7f\xfa\xa3\xfd\xdf\xfdG%8\xd5\xcc\x02\xb7Se\x11v\xc0`\x02R\x10\x90\x18\x0c\xc5Z\x80\x90J\x99\xe8-S\xc87:Wf\xff\x00|\x93\xa0\xaa\x9c=\xad\xe7\x17\xe9\x98e  \xa8\x1c\x8a\xaa\\\\q\xa7K\\C8\xba2S\xc6+\xfe\x0b(\xac*r\xcb\xa8\xf8C\xe8*y=\xf5c`\x0cF%\t\x92\xceZeIR\xb3\\\xb6\x83\xab\x9b\xdd\xfdaPJ\x82\xb3\x02\xf4\tcD\x8a\x93\xae\xbep\xc7j\xa7x\xccJB%\xad\xd9)\xa0\xca\x0f\xd9w\x00\xb0,x\xf1\x0f\x02\xce\x98\x85L\xcc\x99yP\xe2\x81\xd4\x00\xe03;\xf9\xc2\xc91t\x03\x87\xe7\xc2\xd4\xbe\xb4l\x83\x86\xce7MFj\x00\xe9\rgd\x8d:\x00\xe7\x9fH\xd1\xb3\x05U#)\x04\x03G\'A\xe5_x\xf5\xaa\x0b2\\\xfay\x0e\rn\x02$\x94PI\xcd\xb8\xd5fr,5-\xaaE\xf5\xe5\x11\xda\x8e\x14\x80+\xbb\xd5\x873n\'x\x85\xf8\x91V\x14%\xed\xa0z?\xb7\xa4\x056]Y\xf7o_*}p\x83\xe6\xaf(<\trZ\xa1\x83\xf5\xe9\xce\x17c\x14\xd9\x80r\x97\x07\xcf\xfb\x08"L\tH\xab\x0b\xf2\xf3\xde\x0cU\xf6\xa2JTX\x96/\xfd\xbaC\xfe\xc9\xecL\xc0\xceSP:\x1e\x80\x01\xadu<!n7\r\xde)(\xb3\xab\xda\xaeb\xf5\x80\x94\x12\x00Jh\x12\xc5\xc3\x80\xe0\x83M\x0bk\xc9\xe0\xf8\x89\xc4K\t\x177\x8a\xac\x16\x01?\xaa\\\xdf\xf4\x8f\xa7G7\xf2\xcbyv\xa4J\xb0\x00A\xcaO]X\xd5\xbc\xbeq\xa6%iY%)J@.\xda\x02K\xe5\x00\xe8\x1d\xa0\x99* \xa7)\xcc@;\xa4P\x15:Y\xbd\x0b\xf3\x11a\xd9[\x02\x88\\\xc4\x02\xe3R\xe2\xbaS\x85L \x01\xca-\xe6\xcfD\xb0\xe7\x97_\xb4UW\x83\x990)BX;\xd5l\xa9\t*r\x01\x01\x99 \x03\xa3SH(v\x7f\x111\xe6\xa8\x92\xb4\xb1\xa8$\xa8(\xd5y\xac[\xdd\xe9j\xf4\\.\xc5\x08\xcc\x94\xf8T\xc4\x1e\x04X\xd3X/\x05\xb3BJ\x87\x10\xd4\x1e~z\xc3BR\x8b\x06\xef\xbc\xe9\x15\x13~$+\xb3\xb9\xba}\xab\xed\x1c\xaeOeVA*p(\xecA\xcaM\x98\xb7\x94\x1d\x84\xecrBJ\x8a\x89\x06\x8c|N\xde*\x0bkJ\xde:\t\xd9\xac\x95\x0c\xbc=\x85\xe9x\x84\xe1w\x19\xa8\x08?0G\xac\x0f\xe5\xac_\xbe\x91\xe5c\x82\xceW\x8aF\xcc\xec\x8c\xb9$\xacK\x0cwX\x92\xdc\x1c\x02]\xdf1v\xa3yF\xb8\xae\xcaH]\xd0\x1b\xd0\xbe\xb6/\xef\x17\xb3\x85\x1d\xdb\x85Pi\xed\xf8\xb4D\xac1\xa9\x1f\xde\xd5nE\xe3\x84)\xdd\xe2#\x16\xe0\x86\r\xc29.\xd6\xec"2\x15IyDi\xbc\xa0h\x1e\xa4\x93\xc5\xea-G\xb4&\xd8\x1b\x05Rf(\xce\x15b\x00\xe8k\x1d\xb3\x13\x85 S\xeb\xe9\x9f\xf0\x84{GfKRUAZ\xd4\x00A\xa8\x00W\x9f\xdf\xc6\n\x99\xebm\x95\x98\x04\xcc,\x99\xc3\xc06NMn`[\x88\x1eq\xce;E\x82L\xc0\x9d\x005"\xf6,!R\xb6L\x96\xff\x00\xf6\x0eo\x7f/\xce\x1eb\x02\xb3\x14\x0b\x83\xa5\x8f8\x12b3P\x92\x0fKA%\xcc,\x18\xc5b]\'\xe5\x90\x12E\xc9\x0exg\xc2\x80q\xb4 \x9b$\xcb9\x81%\x88#2i\xd0\xbe\xbe\xd1\x98M\xa0\xd3\x02\xcd\xc9\xa8\xb0\xaf\x06\x8b\x0c\xcd\x98V\x18\x17\xe0j\x1f\x84W6\xce\xcb2H\xf7o\xce\x18J\xd2\xbf\n\xa1\x99\x84\xca\x01RV\x14E{\x1aj\x1e/;.zL\xc0\xa2V\x90\x9d\xec\xe9\xa9\x055\x06\x84j\xd5zD\xeb\x98fL&\xaa\xab\x93Gcrh\xdef(\xbb\x13m\x14\x1c\x8a$$\xeb\xf7\x18\xb4\xe1v\x92r\x10\x90S0\x9a\xa8-\x81\x00>V\xd6\xa1\xc9/aN5\xf3\xb0\xeaAch\xd0a1\xc8\x9e\x9d\xa4\xde\xcd\xa6\xbc}N\x8eL3T\xc5)\xd3,eHl\xc2\xf5\xab9\x1e\x8f\x07b\xa6\xca\x9dT\xa8\xa4\xad)\x19\x08\xddBSA\xbek\xa1`\x01-r\xee\xe9\xd6\xa1-\nB\xc3LP\x15\x05\xd3\x94\xd4\x1a\x1fb\xf1\xebwR\x92\xed\x99a\xc1\x0cin\xa0\x92\x0c\x04\x06\r\xdf{\xad\x0e\x82\x0bl\xebKW2s\xe3\x95\x98\x1b\xc5\x8b\xf5\xbc\xef\xb7/\xd3\xf2\x8f"\xbd\xfaL\xef\xe0\xfe\x84\x7f\xdb\x19\x13\xdb_\xf3\x9e\x90?\xd1\xa3wO\xfdb\xaf\xd8\xb9iR\xd6\x95\x12\x02\xb2\x82\xae\x00\x9b\x81\xa9\x8b\xec\x89Hi\x81UT\xa2B\x00\x1e"\x0b(\xaa\xb4HJUA\xaa\xa2\x8f\xd8\x85\xa4*f`\x0e\xe5*\xccHVU?\x10X\xb7(\xbd\xc8\xc3\xc9\x97\x91$\x15\xe4W\xedr\x12R\xb4\xbb\xa5aL\xc0\x1c\xc1<j\r\xe1\x8cQ\xff\x00\x9b\xde\x90\xb7\xc2\xd8a\x10+\x9d\x07\xf5\x1f\xd8\xea\xe2\xd7\x01\xe1\x90\x82\x0fxT\tI\xc8\x02s\\x\x8b\xa80\x0c\xd6&\xa4\xf0\x88\xa5\xcb%\xe5\xa1\xdc\x9a\xf0)\x01\xc59o\x1f\x946^\xccI\x1d\xe7}-)fH\xae\xf9\t\x13\nh\xe0e%)\xa9\xbbV\x06\x997\xbdZEJ(\x00R\x80)KTf`\x0b\x00\xa1n\x80\xea\xb84\xf4\xfc\xc5\x81U\x1cu\xb0\xf3\x15\xb3\x9a\xd1\xb74.\x9f$\xe5\x04\x1a=8\xb5\xd9\xd8\x03\x7f~\r\x1e\x84\x99\x89$\xb6\xed30\x156\xeaXyy\xc7\xab\x99\x94\x9b3\xb8\x05\xdd\xba\x80\xd6\x009\xadCk\x12\xe2%\x8c\xc3\xb9B\x8a<Y\x14^\xc0\x15\x87H\x16\x01\x8a\x86\x91,\xe2V\xcb\xb7\xf5>W\xad T\xac\xaf,\x9c\xc0\x07\xa3\xbd\x0bo\x17"\x8e\x00w\xa5/gQ\x89NR\xa0\x92\xe3\x8by\xb9\xf2\xe3\xce\x19\xe2R\x99\x8a\xdd \x00wh\xc5\x9c\xe5\xe9\xe6iK\xc2\x89\xf3\xd4\x90\xb4\x8ajH\xe4bH\xdd\x00Slk\xc6\xe0\xb3\xd72Hnq\xb6\xc4\xc2\x19\x93\x8b\x07d\x92[G4\xf5\x8b\xac\xd4\x199\xe589\x81\x04\xe6\xdd\xb89\xc1\x1461N\xec\xdc\xf6R\x98\xb7\x87\xfeQ\xd1\xd6\x84\x14\x84eL\xe5\x94\xa0\x02J\xfb\xc3\x99\x00\x82\x80\x9a%)v\xa8$\x90z\x08\xcd\x0e\xb6\'A\xe6\xfd\xf6\xd1\x14\x16\x96\x0b8.\xfc\x88\xab\xb8\x1af5\xb3\xb0=\x9e\xd9\x85k\x0e\x08\x7f\xba:^\x03\x05\x91,k\xc2*\xdd\x92\xc5\xe5=\xd1\x00\x94\x92\x08\x0cH"\xe1\xf9X\xc5\xd8\xc3\x18Ia\x8a\x8d\xfb\xa4g\xbe+\x88\x98\xa9\x9b&\xdd\xd6 \\\xc6\xe9\x1e\xca\x9f\x192[\xc6\xa8\x97Xg\xc4\xf1Z\xc9"\x08L\xc0D`\xc3\xa6#J4\xf9F\xe1\'\xeb\x96\xb10^\xe2\x06ic\x1a\x0c\x15\x08\xa7\xd6\xbdb\x15\xe0\xa0\xf4<J+\x1e2\xd2r\x8e|\xd5&\x12\xe2\xf0n9\xb7\xbc+\xc5\xec\xc0\xa7+%(\x00\xd9\x9c\xd0\xf1\xd6\xf1mT\xa8Q\xb6p\xa5Id\xc0\xa6\xc9\x03\xc4\xd0\xcc\x8cAp\x97m\xf1\xc4{I\x842\xb1\x01\x89bU\x94\xb8$\xa5\xcb;k\n\xa7O\x19\x89\xa8\x1d\x0f\xe1\x0e\xbbi4w\xf9\x1by \x86\x17\x7f\xaaEQ\x12\xa6;9~\x0e\xf0\xbc\x81\xe1\x06\r\x8dD\xc5\xcfR\x92\t\xb5\x81?\xe9\x0f\xac5V\xd8\xc8\x1a[\x93\xc4\xdb\xf1\x84\x98\xf9\x85nV\xa2O\x1f\xabD\xb3$\x96\t)b8~\x02 \xc6\x9a31\x82\x01\xe2\xa4;\x86\x94\x89r\xdfe\x89\x15~\xde\x11),`\xec&!TK\xd2\x06\x9dx/ga\xf35Z\x1bY\x0c\xe6)\xa5"`\x9cQ.\xf0\xc3\xf4\xf5%\x80\xde\r\xae\x91/\xeb\x85\x93\x98\xa0\x97\xd0\n\x1e\x14\x11\x92peD\xb0`\x90Ipt\xfe\xd0\xd7\x01\xb2\xd6\xa4.qJr&\xa5JR@{\xf8MO@=!E\x04=\xa3I!\x13\x92\x97T\xcbj\xd9\xe5\\\x8c\t\xfa\xdf\xf8\x0f\xa0\xfcc">\xe9\x1cLd\x0bf^\x90\xf7\xca\x99\xafA\x0b;*\xb1\xdf\x80lA\r\xa9\xd5\x87\x90\x8e\x8f\xb2\xf1\x04\'\xf6aY\x8a\x88\xcd\xa2\x92\x14\x95\x04\x90hl\x14\xd7r9G?\x18\x05\'*\xc0ct\xb0\xae\xedI\xe2\xdc\xe2\xdd\x81\xc6\x19\x92\xd3,(KIg\xbf\x88\x17\xde\xbb]\x81\x14a\xeb\xec[,\xb8\xb4/\xf0\xc4)\x12L\x99\x9a\xeb\x91\xbd*\xecE\xac^\xba\x87\x931[\xa2ZU\xba\x94\x1d\xd2\x9a\x85;\xa9&\xb7\x0c\xa2\tvJ\x9a\xe4\xc6\xf2\x12&,\x1cRq\x05+\x96\xe9\x009j\x90A\x98\x7fv\x94\xb5\x1e\xa6\x90$\xb5\x82S\xde\xa5\' )\x19\xca\x99D\x1b\x9c\xa4\x13G`\xe2\xcfsX&N\xb2l\x97\xabh\x14\xceM\x81,\xf5\xb9\x14%\x80\x85\x92\xa6.Oyq\x1b\x9f\x9cX|\xba\x1d\x90\xc4\xe7\x9e\xae\xf7\xd3N5x\x8ek\xa4\xad\x19\x93\x90\xa8;;|L\xb2\x0b\x90\x00Q\x15s\xbcbe$\xa4\xcbG}\xbaj\xa5\x80\xfd\xd2VJ&\n\x1a\x82\x97-\xaez\xdc\xc6\x8a\x9b\x90, \xe6M\xd4\xa6\xe2\n\x08\xb8&YpY\xa8Z\xb0\xab\x11=\xa5\xee\xad@\x1239\xe1\x948k\xdc\xd0Xy\xc4\x80\x16\xef\xb2#\x8bP5\xed\xc8\xb9\xa5\x0b\x1a=\xe9a\x01\xe3\xd4\x8c\xc4\xa6\xc0{\xe8\xc3C\xf2xS\x89\x98\xd1<\xf9\xe1\xf447\'W\xbf>\x1da.;\x13\xf0\x88jL\xa2XB8\xbcbP\x82\xa3\xdf\xef\x06\xec-\xa9\xdc\xe2\x92\xb2\x90\xa4>\xfaM\x88\xd0q\xe4\xfa<_\xe7\xed\xc9\x8a\n \x91)jr\x90\x19\xf3T\xa73>[\x9c\xae\xd5v\x8eW\x81\xc2*j\xc2\x10\x1dG\x8d\x00\xe2I\xd0\x08\xbam\x0c\x12\xf0x4\xac\xa9KB\xa6\x04\xb1\xa52\xa8\x82\x9fB\xda\xb1\x89b\xa4\x85\x11\xb2|Q[\xf0\xdf\x8a"Z\x8agY\xdc\x1d\x1c\xd7\x85j\xec\xe0\xbeF\x97}\x9d\xb4JV\xd2\x95,\xa7t\x12\x0eV\xb0H*^PM\x9c\x8e\xa7S\x17=\x97\xb4\x86P\xa5\xa9\x9f\xc25 \xb3\x1e\x8c\xccux\xf9\xf6F\xd9d\x9c\x85\x89\xf1\x05\x00\xda5\xb5\xe7\x17\x1e\xca\xf6\xa13\x12\x993f\xe5\x9a\x18KZ\x8e\xe9\x1fe\\\x08\xa1\n\xb3\x02\xf5h\x07\xcb\x99.\xa9\x1c\xbb\xfb\xc3X\x91\x87\x9e\xc1*\x05\xf3\xcfN\xf4\x19\xe7\x1d\xa7\r\xb4s|0hK\xc5\'g-y\xbb\xb3E04.\x085\n\x04\x16 \x8dDXdn]u\x83\xc9\xc4\x15\x0f\x10\x8a\\F\x14 \xf8O\xa9\x86\xa5\x11\xbaDy"x1&Hp6Q^\xa2lc\xd0#f\x8cH\x8fbq\x08\xc1\x10\xcf\x96\x0cM\x03\xe2\xe6\xe5I7\x88\xa9A!\xccxG\x02\xff\x00\x110}\xde9a\x89\x04\x02\xec\xf4\xa8\xb9\xe1\x01a0\xe9\x08R\xd2\xa7!\x99\xc9r\t\xa9\xad\x03V\xfc m\xa5\xb5\x7fI\xc5\xcc\x9e\xaa\xa5Jv\xe2\x03\x06vp\xe0z\xc3\xa9;=K*\\\x89K\x99$\x10\xa5n(\x84\x97v5S\x06\x0c\\\xfc\xe2\xb9jj\x08\xd9\xe1\xa5+d\x15\xdf\\\xa9\x93\xd8>]+\x00"[8\xcaI-W\xd5\xecC9w\xe3\xeb\x02\xce\xc1\xa4\xe6\xef\x13kr>v\xeb\x0e\xc8\xce\xa5($$\x00\x02\xae\x12\x9b\x01}I\xaeQ\xcd\x83\x08\x1a\\\xb9\x93\x94\xb1\xe27$\xa8;PT\xa8\xda\xa1\xcf\x9e\x90 \xb2\xf0\xda\xa5\x86;T\x19\xbeG\xd3\xf3\xc6\x94\xed\xa3\xb1@\xdeA\xa7\xd9?\x95\xbc\xe30\x88\xa4[1y\x9c\xe7\x02\x8dP\x1a\xa3\xa6\xa7\xde\x14\xce\xc3\xb2\x8b\x86\x06\xc5\xa8\xfa}r\x83\xa6iXc\x15\x93\xb0\xc9\xc3\x139\x01\xb5\x1fkeS\xed\x11\x84d\x00\xbd\xec\x1bV\xb9\x82&KZ\x92\x14\xaf\tff\xb0$\x07\xd4\x0b\xde\xfeP.(\x80\x1b\x8f\xd3\xc1\xdb.h\x15\x00)CU\x00Xq\x00\xd0\xf9\x86\x88\xac4\x1f\x01\x89T\xe4\x95\x11\x9d8D\x7f\xa2\x0e?^\x91\x90\xf7>/\x84\xefU~\x11\x90\x1a\xef\xf2\xfc\xc5\x8f\xcd\x1b\xbf\xdd\xf8\x85\xe8@\xa9!\xda\x8c\xdcA\xde\x7fJ|\xaf\x02H\xdc\x99f\x07G\xd4j\xf4\xb7\xe5\x11w\xea\xcc\xe0\xb0wken\x15\xbc\n1\xbb\xd9\x98\x12\xe0\x87\xb3\r\x1bX \x96D@\xcfI\xef\xbe\xf2\x8e\x97\xb3%\t\x80\xe7\x93Yr\xd2\xa7)/\x94\x19I\xcc\xd4\xcc\x02\x1c\x865rO8\xa6I\xeff\xb9\xcb%,\x14\xe9K\xa4:\x98)N_)$qghU\xd9\x9d\xbe\x99\xa7$\xd5\x12P\x96J\x16\t7HIHfP\xddH\xcbJ\x1a1\xca`\xfcF\xd9\x19\xe5\xa9\x83\x84\x00\xeaK\x82%\x93\x91\x83$\xb09nHt\xd5\xc5 *\xa3\x83\xfb\xd4\x9e6\xcf\xa0\x88\x87W\xd28f\x06t\xa1r\x1a\x94\xf0\x9c\xa1N*hJ\x0c\xa0\xc0\xa8\xef)LlCTX;\xfa\x97z5gj\xe2,3\xee\x81{sn\xaeI{\xc3\xcd\xad\x8cP*Fp\xaa\x92T*\xf4\x0e_\xdb\xd6\xf7\x84\x18</xFm\xd0\xec\x90\xad\x7f\x88\xf0\xea`\x92\x83T\xc7\'\xa0\xaa\x89\xb9\x7f\xde\xcfj6C\xc3Sg]\x85\xd9I\xc5\xf7\xa8\x98\x93\x97\xe1 \xb1\x05OT\xf04MO\x0b\x18O\xb4\xf6\x02dLZs\xa2jR\xaf\x1aT\x95=\xd8\x16;\xaa\xa5G\x18\xb0l\xe9\nH\xee\x92\xb0\x8e\xf01!\xca\x94\x9e\x0c+\x96\xa4\x1e4\x11*\xf6"\x14\x92\xc4\xa8X\xb2M\xec\xce\xc0>j3<\x14.\xe4\x16|\xa3/7\x10%\xe2\xc8H\xf9\x82\x83\x9d\x8e\xceYs\x1c\xe0\x0e\xce`B\x94\x94\xd0fu(\xd9\xa5\x82)\xcb2\x99\xf9$\xf1\x8b\'k6p\xc5!\x18t\xbaD\xb5\x92I\x06\x84\x02-z\x0c\xd7\x8c\xd8\xbb\x18\x04\x92\xc71H\xa8\x0cK9\x03\xa0\xa1\xa7\x03\xc0E\xd3e\xec\xb0A\n\x15\x06\x8c\xc4i\xe4E\x9bH\x00Z\x8a\xfc\x17\x87\x97\x86\x96\x85\xaa|\xea\xb9p2\x02\xc1\xee\xec\x19\xd9\x83\x8a>|\xdbe\xff\x00\x87RJ\x88\x98f)\x90\xaf\x11\xca3\x84\xb8v\x01T!\x99\xff\x009g\xf6&R\xd3\xbb(\xa1u\xdeB\x947h\xc4\x07!\xc1\x06\xad\xaf(\xec\x18=\x8e\x18\x15]\xab\x11m=\x98\x12\x96\x96\x18\x9dy\x08`\xa3\x10\xdbEF\x04\x9cV\x18+a(\x15l\x9cQ\xf5\xe3\xd9\xacr\r\x91\xb6\xb1xI\x86\\\xe9\x86`!\xa5\xae\xe7(\xf1&\x96g\x14\xe7K\x98\xe8;\'\x16WU\x16\xa0z\x83p\xe2\xd4\xd6*}\xb7\xec\xe2\xcc\x85\x16b\x1dH\xe3\x9d6n\xb6\xf3\x85}\x84\xda\xe6jT\x8c\xdb\xe8\x01YXo\x0e\x01\x86e\x16.\xcfd\xaf\xac\x00\x05\xa9;MQq\xef\xce\x1eX\x94C$\xf3%\xcd\xecI.\xe9\xdf\xfe\x9a\x92\x08&;V\x1b\x10\x94\xa4e\x0e\xfa\xf3\x83\xf0\xb3]\xfe\x84U6v \x10M\x05\\\x8b7 \xe5\xfc\xa1\xe6\x1dJ%\xbe\x9b\x9f\x03\xca\x1b\x939\xda(\xe7\xc8\xd9xp\x0c{\x02\xca\xb9\x0e\xed\x12\x19\xad\xac8\x0cW\x94\xd6\x91*\x8c#\xedF52\xe4-Ea\x0c\x0e\xf1\xd3\x9f>-\x04\xe3\xb6\x9a\x10\t&\xd1\xc6\xbbq\xb7\x15\x8a\x9e%;JIp\x05]V{\xd5\x83\x86\xe7\x0b\xcf\x9a\x86)5\x8b\x0c\x0e\x01s\xd62\x11^\xc2H*\x0bY\x04\x97\x04\xa9D\n\x97\xa5Fe(\x97,\xfciG\x16M\x9d\x85X\x0b\x00J%\xb2\xba\xa6\xa5%7\xdeG\xed\x06aS\xc4\x18\x1bf\xa3"\x88B\xd4\xb9a\x9dHp\xe8Sf\x01\xec\xe0\x01ZP]\xa0\xb5\x15\x04\xadh\x0bH\xaa\\\x81T+\xe1Pf\xa8\x07\x88\xa7(\xacR\x82\x8d\xa3j\x13\xb2\x96\x16\xa3_so\x1apf\x14\x80\xb1i\x9b)fZ\x8a\x90T\x00Pvz\x02\x1d\x8b(p:\xd0\xeb\x1eb0\x0eQ\x90\xd5T\x01D\x06u\x11Ux[\x9d5\xb3F\x93gx\x16\x9c\xc4\x83\xba\xb7\xb3e\xcaF\xa0\xb8W\xfe\x98\xdf\x13\x8e\x98\xa0\xbe\xf1D\x95\x17.*\xe6\x8ei\xaby\xb4z\x803w\xd2:R\xa7\x0c\xdb\xfd-_Z0\x02#\xc5\xa6j2\xa9a5$U\xae\x92\xdf\r\x98\x8dxp\x85x\xe0\\\x85$\x83f4)P\xb8\xf5x\x92t\xd2\x13\x97A\xa7\xacC\x8d\x9f\x99&\xa7\xcc\xb9\x1c+\x7f8\x92\tx^rX9\x02\xdc>\xf4\xef8\xafN\xc4\x97/\xa1g}`\xd9d\\\x17\x1cM=\xa0T\xec\xe5MQ\xc8\x18q<^\xd4\xd6\t\x99\xb2\xd7\'\xf7\x99T\x07\xc2\x14\xc5\xd9\xc5\x08}A\xf6x}hI\xa4f\xf08\xd1%fY4\x16\x86_\xadO\xff\x00\xdag\xaa\xbf\xee\x8c\x85?\xa6s\xf6\x8c\x88l\x9d\xfeqs\xf3\x93\xbb\xa7\xda\x1e\xcd\xc3%\x99Z\x10\x00"\xb5~U\xe0zz\xa3\xc4\xe1r\x87\xaf!\xf7\xfau\x8bL\xc0\x19Y\xf977\x0f\xd0\x0bkc\xa9\xa4(\x9b*\x95\x1b\xa5\x9a\xba7\x0fx\n\x14A\x86\xa6\xcaJ\xd2\xc6\xff\x00\x8e\xbeq]\x95\x8aR\tRK\x16!\xefC\x05\xcc\xed,\xf2\x00YJ\xcaC\x02hY\xc9\xf3\xa9\xfb\xa31\xd8\x1a\xb0\xd1\xf4\xf1}}\xf0\x92pbA\xd2\x1dJQ3(\xcfb&b0\xa6\x84\x8fN<b\xdd\xd9\xc4\x0cEf\x82\xba\xee\xa1\x14\x07\xff\x00+o\x1a{\xf1\x8e\x87\x84\xec\xc4\x89\x89\x04\x85 \x81QG=iJ\xfb\x8e\xa2)]\x91\x90\x0c\xb4\xb1\xcaF\xaeu\xf1[\x9d(c\xa3vnz\x98\x99\x8a!2\xc0Nr(\xc6\xc5Z\xd8\x00\xf5\xa0\x11]=N\xb2\x13\xafy\xc3\x93\xe4\xe2\xa5\xc8L\xd9ST\xec\n\x86\xd1\xa9-Q\x91\xc8\x01\xe5\x15\xd1&^\x0ej\xc4\xcd\xf9\x89S\xa1\x87\x89\x04Q\xea\xc9g\xe3\xa4M\x82r\x00b\x91\xbc\xa6\xa8.\xb7.y2\x9f\x81\xa4\x06&\xf7\xb3&\xcep\x02\xd4\xa25*\xab%\xde\xc9\xa0\x1e\xd1b\xd88\x07\x0cT\x1c\x92\xdfW\xd6\x9f\x94\x06if\x02\xe6+\xfe\x13$2\xb1\x0b\x14\x14N\x8f\x99\xe5F\xde\xfaCM\x99\x80\x19\x12\xa4\xe9z\n[\xf3\xfax\xb4\xe00\xc0\x1c\xc3P=\xa9\x00l|1\x96\xac\x8a\xaf\x1e`\x80\xc6\x1fK\x94\x13h{\x0b%\x83\xf6\xf1\x0cn \xa9D;\xfd\x8cK\x96\x03\xda\x8b!\x14\xf5\x83\x1e\x06\xda\x12\x8a\x80\x03Xq\x7fIhBW\xd6\x1e9\xfe\xd7\x97\x98)\xc9\xfb\xa3\x89L\xc5.F"f[\xa5j\xb1\xd33\xe8hc\xe8\xbd\xb9\x87\x96%\xa9,\xeapK\x1b\xb1\x0e=\x1e8Wl\xbb:\xac4\xc4\xaf(\x12\xe6\xb9I\x06\x8e\x92\xca\x00_\xe8\xc5~\x1d!\x13\x14\x95f=\xe2\xeet\xf5\xaa@\\\xbal\x9el\xcdMF\xbevv\xb3\xf6{\xb5\xe8Xd\xee\x90\x1dIR\x9d\xb8\x90Z\xded\xc7M\xc2\xed\xd4\xaeJ\x14\x95\x87P\x05\xde\x8dKq\xa1\x1eM\x1f0\xcd\x86\x9b\x1fn\xcf\xc3\xee\xcbY\x08w\xcaj\x97\xe3\xc8\xf4ga\xc2\n\xac2\x92\xe6Q\xbe_\x91\n\x9cr\'l\x89\xc9\xb6c\xdc\x1e\xb5\xe0\x00\xa0\xfarF0\xa5\x1d\xed2\x92C\x8b]\x81\xe4\xec`<~\xd9\xca\x95(\x9d\xca9\xd0\x13\xab\xfc6\xbcr\x05\x7f\x8a\xb8\xd1(\xa4\xa3\x0e\xa4\x10\x12\x90\x10S\x95\x8b\xe8\xaa\xe9\xfd\xe1\x0c\xfe\xd4\xce\xc4\xee\xcd[Xe\x01\x93O\x0f:Q\x9c\xe9\x12R&5\r3\xe3\xf6\x8eH8u\xcce\x1b\x9ap\xe9\\\xb9\xc5\xd7m\xf6\xb1S\x02\x93 \x15&\xae\xb6\xb0\x17g\x0f\xe7n\xb0&\x07b\xa4MJfL\x96\xeb*O\x89\xc8/\xbaI\x14\x08W\xdar\x18\x93\xa3B|&3\x11\x94)*PJ\x8b\x158\x00(\x8c\xacO\xc2\xe0\x17{\x81Wa\x07\xe1\xb0\x0c\xa5&d\xd4JP\n\x0cX\xd5\x81\x0cj\x005\xde\x06\x9c\x9cB{;>\xfd\xf6\xdaF\x9eV\xcaR@ prr\x1a=\x0e\xee\xb46\x9e\xca\xa8J\x98d\xe7\xde\x9a\x95\xa0\x82\x90\x9e\xea`\x04 \xbe\xa3\xdb\xd2\t\x96\xacF^\xef\x11\xde\xa9\x05+\x13;\xe7\xee\xd2@9&!Vw\x1a\x1a\xd49x\xad\xe0g\x94\xcb3\x92&\xa5I,\x95\x82\xe0\x12\x08)6){\x82\xefv\xe3\x02\xcc\xc6&b\xd6\xa9\x81K$n\x95,\x86\xf6\xabP5)\xed\xe0\xb2\x90\xcehy\x10k\xce&\xac>\xda\xd4\xa0\xd5\xb9`N\xd0\xa0b\x0bP\x10\xd5$\x14\xe6~\xa3\xb0\x13%\x9c\xb2\xceTx\x92\xa5\xa9D\x02\x93\xe1Q\x0ej9\n\x84\x8b\xc2\xf9\x9bUi\xddQ$\x90\x12\tb\xc9P\x0c\x1c\xb9\x03-\xac\xce`\r\xa76\xa1 \x85\x04\x8a(\x0b\xea\xce\xc0\x92\x1c\x8c\xc5\xf4\x0e@\x11\xac\xd5KYt\x80\x87\xab9)\x0c+z\x8di\xe9\x11\t\x86\nR\xeeE\xeb\xc2\xfc\xea\x0e\x9as\xd937\x14\x19%\xcb\xbbT3\xb8\x1c\x8f\x08\xd1(T\xe2\xd3\x14JR\x83\xbd\xa8Jk\x95\xf5\x1e\xb7\xe2\xd02\xe6\x95\xb0\xdd\rB\xa1J\x07\xbbS\xcd\x9c\xb0\xbc5\xc1K\x95/\x0e\xb2\xb2L\xc5\x86JE\xc3\x10}\x08\x17\xd1\xba\x08"CE\'\xc4\xe7\x84\xcb-C^\xbca\x0c\xecx\x94\x83\xdc\xe6C\xeaH%\xadf\xdd&\xf7<!,\xf9\xd33o\xa8\xab5s\\\x90u\x86\x9bO\x10\x16\xa0\x94%\xb39\xe9\x02\x9c\x11=\xd4\xb2Y@\x80\xa3\xc31$\x8f+yC\xc9 \x07=\xde2\xb2\xe8\xa0H\xbc\x0f^*\xf6\x8c\x8b\x87\xfd9/\xec\x1f\x7f\xc6=\x81~\xa5\x10\xe7\xcf\x97\xfc\xbd\xf9\xc1R\xa6\xb2\xff\x00j\x85\xa9\x17(|\xbb\xd9\x00I\x01\x88\x05\xb5j\xf1\xac\x01\x88\x00\x93V\x00S\x9b0\t\xe89p\xf4a\x88\x9er\xa5.\xe1\xbcNj*S\x7f\x08\xa9\x14g{@X\xb9E\x08\xcah\xeeAz\x17\xca\xdf\xf2s\xce\x16\x11\xb6RCw\x95\xfb\xe0\xf0\xb9i\n.\x18775\xb0\xaf\x8b[\x08U\xb5p\x05@\xab\xe2\x03Mt\xac<\xc4#.\xe6\xb6\xa3\xfd\xa2\xef\xa9\xab\x06o\x86\x06\xcbB\xa7u7\x16\x05\xde\xbf#\x06B\xf6H"+\xb12D\xd9E$;\xdb\xca\x85\xf2\xdcy^\x91b\xecGg\xe6\xcdBU\x95(O51\xf2\x02\xb4\xbdY\xf8\xc7K\xd9\xf84I\x94\x10BV\x12\xeaZ\x94\x06\xf1!\xde\xc3(\x01\xe9Vx\xe4\xfd\x98\xed$\xd93S-\x98\x03\xe2\x01\xd9\xb8\x8b1\xa5\x99\xd8^:\x1a1\xea\xc4Q)R\x10\x90\x14\xf7r\x1c\xb1k\n\x1aU\xdb\xa9\x01\x9a6I:\xf7\xdf\x95\x89\x8a9\xb3\xf1S\x96\x99\x0bPH\xdd\xa0\xcf\xf9\xada@M\x84A\x83\xc2&l\xc5\xa3\xba\x12\xd2\xe7*BY@\xa0\x12\x01j\xd6\xcd_`\xcf\xb0XP\x80\x9a:\\\xbb\x1a\x8c\xcd\xe5p\x0f\xad\xa3}\x9b)\x05\x9d9zPR\xcd\xc1\xa8D8L\xbc\xa5)S30-CW\xaf\xd5#\x92\xe5?\x8b\xbb\xbc1:xH\x12\xd0\x18\x0c\xbdZ\xf5>\xa4\xea\xd1.\x02[\x80\xf7\x14\xf4\x83\x97\x1ea\xe5\x04\x82\xd1\xed\xeb\x16HN\xca@\x8ae\xabiD\xc6\xa1Q\xbe!L\x98\xd1"\xb1*\xc6\xecN\xb1\x12\xce"\xad\x8f\xc3\x93sS\xa4Q\xff\x00\xc4\r\x92\xa9\xf8p\x80\xd9\xe5\xb9\x97w/\xf0\xff\x00\xba\xa3\x88\xe1\x1d\x1b\x16\x9d\xe7<\x0f\xde\xc2\x11c\xe7\x04\x17 \x90\xc4\x16\xd4\x1e\x1c\x085\x1d\x04U,l+h\x16\xad\xf9\x88\xbb\xc3\xafll\x10\xe0\x83N \x83\xd2\x9c\xf2\x8f\x9c\x04\x82oN\xb0L\x8c\t)&\xa4\x0b\x91\xa7\x07\xe1\x07m)Yq\x13\x81\x15\xef\t\xfe\xaa\xfd\xf0\xc3\x05\xb3\xbb\xcc\xa2]Tt4k1sJ\xf0\xe5\x0f\x19\xc7d\x11\x9cJO\xc3%\xed2\xaa\xd9\x9fXP\x9c\x06d\xf8\x85\xed\xaf\xca\xd1\x0c\xed\x94\xa0wMx\x1f\xed\x16\x94 \xac\xa4,\x9d\xd0\xc1\x92(\xce@\xd3S\xef\x13"QYPX\x19\x8dB\x8a\x99\x80\xa9\x15!\xe8\xcc)\x02\x18\x82!\xb5\xfc&I\x15K\x1d\xc4\x8e\xf7\xe9\x15Tbf\xa19T\xe1 \xbb;\xa4;\x02i\xc6\x9e\x9c\xa0\xbc\x1e/{\xc4\x039\xbb;\\\x03\xc4\x88i\xfa3\x82A9\x9ciB\xe7W\xabz\xc0\xb3\xf6:j\x93\x95\nM\xf2\xbf\x9aC\x02=c\xbbiU\xc3D\x86\x1e|\x90\xc9S\x8d\xff\x00q{\xd6\x82%V\xd0H;\x85A%\xb3$\x91V/\xa5\x08\xa3\xd7\xdd\xa0\xe3\x8d\t\x00\x85\x85\xa0\x92r(\x02\xca\xa0$\xe9kt\xd2+\xea\xd9\xf3\x10\xa0P\xca\xad\x8e\xad\xca\xc7\xa4@q\xeaJ\xdd\xb2(\x17aF/\xa0\xd0G\x0c\x90\xa1\xe1\x89\xfe\xb9R\xce\xcc\xe0\xdcj\xfc\xfd\xe2\xcd\x8c\xc4I(\n\x96\xe9X\x005\xd9\x85M\x839f\x00\x9b*\xce\x04A6|\xc9\x81)#1S1\x0cT\xd6\tq],y\xf10\xaa~<,\xa4\x9a\x92*@7$\xdf\x89n\x03\xd6\x07\x9d\x89$\xe5\x1e\xda\xc4D\x92\xf1\xe5\xe3\x90\x03\x83Z\xdc=\xf7\xd3\xdd\xc7\x18\xb0\xecU\xa0\xac\x95\xa9\xeawr\xdd\xeb\xa0f\xd5\xb9A\x98\xc5!$*\xe1.\xcc\x9aP\xd8\xe8\xa7\x8a\xde\\\xa1\xdf{-C\xf1 \x06\xf2\xd2\xb6\xe6\xc0\xa3\xb4D\xc1\xdd\x80J\x88jR\xff\x00O\x1dR\t\x8c\xbc\xf0\x99\xb3\x1aX\'\xbd\xff\x00x\x8fe\xa0L\x9f\x9c\x05eP`\x0f\x11p\x0f\xa9\x8bT\xbd\x8a\x82\xcaJ\x19H!\x94\x05\xc77\xb8\xbc{\xb16\x01\xca\x96K\x1aP\x9f\xa1\xc3\x84Z\xa4\xab\xb9\xca\x86\xa9\xe2\xd6\x17xVv m2{\xfb\xc4\x12JHj5"\xbd\xdd\x9e~\x87\xf0\x8c\x8b7|\x9f\xb5\x19\x0bm\xcc\xd3\xa4Ka\x1b\xfc\xa2\xa1#\n\x95\x9c\xa5I\x00Tg,\x0b|%V\x0f\xcc\x8e\xaeD\t\x8e\x19\x96\xcbRBT\xa7z0\xd5Yj\xc7\x90{\xc3\xcf\xd0\x92\xb9ft\xb5\x01\xa2\xd0\x14\xf4z\x12\x92\xe4\x82\xc0\x8a3\x80\xd5\x85Rp\xc8Rf\xe6VR\x06\xe6\xf3\x92\xb5:\x9d\x85\xc3\x06\'\xe1*C\xd1\xd9\xc2\x1a7A{N^\xd4\xb5\x89\xa7;\x8d\\V\x94\x10\xa2|\xbc\xab)\x04\x964#\xcf\xcd\xcf\xach\x999\x86bS@Y\xf97\xb4m\x94\x10\\\x9c\xd5rl\xf4`*\xfc^\x9a\x08+\x0f\x8cH\xee\x89L\xb0\xc3*\xb3\x00R\xa4\x9f\x89Vb\x1e\xefF\x06\xac_\xa2\x07\x88\x05(Q\x03"\xfc\x81\xa6\xa0\x1c\x9b>1\xa6\xcf\tC\xade\x8d\x185G>\xa6:\x7fd\x8eIi.s,\xb8\x04n\x9a\x10>d\x1eds\x8e-\x8bE\xcaJ\xb2\xe5\x0e8\x12\xff\x00\x84vn\xc7\x95b0\x92f\xbaA)\x14~\x0c\x9a\x03j\x8e?\x10\x89,X\x8eQ\x9d\xfd"\xa5)j\x9cA$\x8a\xf1s\xd4\x81\xbc3P\x16\x8b4\x90\x95U\xb2\xa80m)\x0c\xb0\xd2\xc9\x19N\x96?t\x03.J\x82\xabPl~P\xe3\tQ\x0c\xc9Mk\x08OU)\xfbD\xa4R#\t\xa4LDcCM\t\x03\x11\xad1\xe9\xb4nDx\xa1H\xecy\xe1F) \x17.yBM\xad$\x94\x9e\x14\xfb\xda\x9e\xb1a\xc5I\x17Q\xf2\xe3\x00c\xf1a;\xa9H\xb1\xbe\xac?#\x15\xf3\x90\x0b\xb9h\xb2\xc3\xcc \x82\x9a\xc7\x04\xed\\\xa4\x8ca\xe6\x80i\xaa\x83\x8f\x93zA;/g\xb8~\xf0 \x06`\xa2\xcaQ,(\xc0\x81{\x92)\xc63\xb7xS\xfaVw|\xc94\xfeVf\xe2?\x03\x12aB\xe9\x9c\x14\xd1\xb8\x12\x05\xc7\xe3\xce\x86\xb0\x14\xff\x00\t1\xa8\x90\x06\xd2\xb7\xfd\x81\xef\xb2\x0f\xc2\xccS&\\\xb0\x94\xa9\xcb\xadD%$\x16`T\xa2\xc4P\x96"\x9c\xe0I\x89\x04\x17\xcb\x9c\x9b\x87v\xf5\x01\xa0\xa5\x15\xaeX)\xca;\xb1fBK\x83pA\xcc\xb3j\x97 \xbe\x91\xbe\x11\xd8\xca\x0cU1A\x89@R\x89/\xf1\x00V\xf6\xa0wx\x843\xf4\xb9n\xdf\x85CW\xde\xb1\x16+\x031\x0b\x01i\tS\\\x16\x07+\xef9\xa1\xea8@\xab\xde\xccH.\xaf\x89U&\xb7.\t$\xf1}`\xc4\xa9)P\x13\x10\xa5\xa5\x00\xa7t\xe4\x0es1\xdeK\x9a\xb8b\x01\xe3\x13I\n%2\xd4\xb2\x12\x80\xa3E\x82\x13RU\x95\xd5\x94\x97\xd1$=k\x12$\n\xf7\xe7\xa4A\x98:\xb9\x9f2\xf7$e}EHx\x01Xr\xe7\xbcY\n\x00d\x0cK\xf0Is@\x1b\x81\x10\xb7\x17\xb2\xc2\x9e\x99\x94\xe4\xb1\x1cxk\x7f\xae/Q\x95\xc8!\xcb\xbej\xb1\x009\x07_\x7f\xc4G\xfaj\xcei\x9e*\x04\xef>\x95KW3\xa5\x81\xcc\xf4\xa3\x9a\x87\xf0Q\x11\x05J\n\r\xb2\xfe@n\x16z\xd6\xf9\xf9\n\x06?\x04e\xd4\x17\x1c5\x1d`!\x89 \xde\xadN\xb1u\xdaXUKR\xbb\xc4T\x822\x9a\x97 \xb1\xa5\x05\x81\xf3\x06\xb1J\xc6I\x01jf`M\xa2\xc2B\xc2\xc5c5\xf1,8\x94v\xa5\x17I\xe7\xe4t\xeft\x1b\xb21%\n$\x80\xa0A\x04\x1dB\x83\x11\xe8tcG\x0c\xd1q\xd8s\xb0\xfb\x99S\xdd\xe5BB\x9f\xe2X\x1b\xcb\xa0\xa6k\xb4T6l\x97"\xbf\x94\\\xfb?\x85@U@&\x8cK\x1f@\xd0\xb6-a\x88\x80\xfe\x96\\\xb9_2c\xb1\xa0k\xbf:s\xaf\x08\xbal|t\xbc\xc0\xe6\x0cu\xbfAH\'\xbc\t\x9d\x9dIt\x9fg\x85\xd8\x89\x89\xca\x97\xa0I\x19R\x9dO?\xb4O\xd5\x04>\x90PB\x932\xadujb\xa9\x88\xac%\xb2\xc3i\xa8{\xdc\xfd\xef\x80\xff\x00T\xa3\xed\xa3\xfa\x07\xfd\xd1\xe4\x15\x93\x0f\xfc^\x91\x91\xed\xa4\xe9\xd6\'\xf3\x8fb(\xf3\xb0\xea\x96\xff\x00\xc0\x92]\xbe\xd0\x14-\xa1jy\xc6\xd8\x99\x92\xfb\x87I\x01I\xc8\x0bf\x01y\xddD\x10\xaa\x12\x822\x93cC\xc4\x97{Fx\x9d6jBR\x01K\x94\xa5OT\xa5JQs\xa9\x084j\x15\n\xf1\xa4.s\xd0\xff\x00g\xd7\x9fHx\x80\x92\xc3|n\xe4\xac\xcdN\xd2\xe8C\x1ap}+Wm\xf5\x15\x00\x88T\xe0\xe7\x1c\\u\xfah\xf3\ne\xe5S\x82\x17\xa0\xd1\xbf;yF\xe1\x04\xab+\x80\rjY\xd8\x13\xea\xd4\x1dc\\\xae\x03jM85\r\xfa?\x9csj\x91\xd5 \x15u\xa6w p\x85\x98\x94\xb70C\n\xbf\xaf\x03\xf3\x8e\xaf\xfe\x18m\t\'\x06d\x84)SP\xb5g\x00\x02\xbd\xe5\n\x80\xc4\x9a;\x16\xa5j\t\x8e]\xb4\x15\x99\x94\x13\x95\x89\xa0&\xe4\x93Gr\x05Xt\x84\xc9\xc5.\\\xc0\xb9j)Ru\x1e\xe0\xf1\x1c\xa1\xb4\'i$\x08\xa1\xc6\xafa@)\xea\xce\xc7x$d\xecCd\xed\x94}O\x86Vb\x9b\x82\x05\x13u1\x14r\x07\x03\xe4\xd0\xeaJF\x91\xc9\xff\x00\xc3n\xd6\xa2d\xb2\xa5\xcf\x97.h!\x05\x0br\xe8\xbb\xcb\x0e\xe4\x15\x1a\xfd\x9b\xeb\x1d?\x01\x8e\x13\x1f\xd7\xc9\x85\xdb\xac\x12Aj*\x87N\xff\x00\x11O\x8c\x94At\x17N\xa1\xfd\xfe\xe4\xeb\xbc\xf8\xd5\xa3\xd3\x18\xf0\xd1\x8a\xe7\x8ch\xf1B=\x8f\x14c\xc6< ,T\x92yB\x8d\xb3\x84\x02YPU\xb4\xeb\r\xb1\xd3\xb2\xa4\x92Z)]\xac\xdb\x02\\\xb5\x07\'0\x01\x81\xd0\xe6\x146\xd1\xbc\xf8B8\x82\x90\x08j\xf6\xddb\xd3\x05.b\xd46c\x94\xed\xf5\x19\xf8\xb5\x10(\x84\xd4\xe9ws\xe6@\x8b\x07g\xf0&b\x02\x8a\x151)Z\\$fe\x04\xa8K\x19\\;\xd8\x12X\x0c\xc3\x94*\xd9X&YT\xd2Q\x9cg%(\xce\xd9\x9d\x8bP\x8a\x1auLX\xa4\xe2\xe6!\n\x9b\x86\xa4\x90Bs,K&aU*\x14\xf9\x94Z\x89\x14H\x1dITl\x86I\xb0\xd2\xef\xed\xdbi\x1a\xaa\xec\x14\xa5\x9c\xeb@\x1e\xc1\xf5j\x86\xcfu\xf3\x0f\x81b\x04\xb5\x8e\xf0\x83\x99 2NE\x02\xa4\x85+qt&\x95K\x8d\\G\x98\xdc#\x02g\x85\x05\x92\x1c8Q\x0e\xc4\x95\x12B\x89!Ia\xa0#\xa0/\x0b\xb6\n\xd0\xa5\xa5BB\xe5\x8c\xca(t\x95%E\t.Rs\x05g\xcbO\x8f0&\xc0\x8f6\xa6\xd1*\x92\x99\x87)PRS1D\x00\xb5\x15\'2j(\x1bx}\xa4\xb0\x15j\xcd%&\xdf\x8f\'w\x1b\xdb\xda\x04\x0c\xcd\xb0\x08\xcc\xd77\xd1\xc0nd\x12\x1d"\x8e@\xc5l\xc3\x98a\xca\xd6\xb5$\x15%)\xb2B\xb7\x86e)A\x12\xd8o2l\x15R\xf0\xa4\xf7}\xda\xfb\xc2D\xcb\xa1nX\x84\xa42K\xd0\x8a\x04\x82*\xe0P\x82X\xacV\xd2*\x94e\xa5\x974\xe6H#1Wt\nH\x04\xd1\xd8\x82\xc5C\xc2\xa2-HK,\t\x85"Y\xcb1%\xeaZ\xc1\xc9\n#t\xf2\xaf\xb0x\xa8\x80i\xdb\xeb\xdf\x06\x89\xca\'d\xaab\x99\x98\x96\xa3\\\x93\x9f\x84\x90h\xc6\xccJ\x81\x88\xf1\x98\xa9{\xa0KXP\x033\x92IST\xb1\x01\xba\x17\x82\'\xcey!\x1d\xe2YNM\x17\x9d%9\xc2RsS-MG\xda\xaf\x08_3\x1b\x9c\x14\xaf2\x8b\xd1\xd5\xadE_[\x01\xc3\xa9\x81\xf1\xbbEHJ|BbAK\x92h\x8be\xb7\x85\x9f\xd4\x00\xda\xc12\xceW\xefq\x8e\xe2\x16C\r7\xee\xbf\x89\xe8\x1c\xe4\xee\x90\x18\xa5\xa0\\V+(b\xa0n\xceA\xa8k\x0b\x8b7N\xb1_\x98\x87\xdek\x96\xf3\x8ff\xe2\n\x8d\xe3EZ,%\xa3b(\xf1\x18\x8f\x9e\xa2\xae>\xdf\x88#f\xcd\x00\xb1\xd3Gh\x7f\xb3\xf1\xd9u\x1d4\xa8\xbd\xc3\xb5\x0bE1s\x19N!\x8e\x13h\xd0\x8eL_\x83\x83\xf3\x8fN\x91\xb5Q\x11\xc2\xe3e\x80eL\x00\x8d\xfd\xe9\x17\x14\xedE\x1e\xed\xd5\x98 \x14\x8e\x03x\x96\xe7p_\xee\x02/\xf8\x0c`T\xa7\xd0\xdfM*\x1f\xce\xd1\xc7\x11\xb5\t\x0cn5\xb8\xeb\xf7zC\xf4\xf6\x86g\xe8\xe2S\xebC\xc0\x17\x7f>}a\x19\xb2V\xef\x0c\xe3\x12\x8c\\\xa4&VG\x83\x03zE\xdb\xf4\xb4\xfd\x85\x7fI\xfc##\x9dw\xdf\xc6\x9f\xea\x11\x90?\xd3\xcb\xd0\xf4\xfbA?\xe1x\x7f\xe60\xf7\x12\x99\x89r\t\xb9\x04\x8dt \x9dA\xf40\n\xa6 \xcbb7\xc1\xa2\x85\x1d\xd2\x9a\x1e\x8cm\x0c\'OZS2Q\x1f\xbcR\\\x10\xccF\x9c]\xc9\xa5\xaa\xfc\x18\x0cBs\x16J\x1a\x81\xfa\x80\x01\xd7R\xe5\xe2M\x17\xabS\xdf*\xdf\x83z\x91\xc8\xf0\x10\xc9\x97\xab\x1eg\xad\xa2Y\x92\xcaIK\x02\xf6p\xd6\xeba^\x86\x90\xcbel\xc5\xac\x86%\x85\x01Q`.Y\xcd\x00rO\x9b\xeb\x1bm\xbd\x9a\xa4(%\'9RB\x89b\x12\x1d\xc1K\xb1\xde\x7f\x98\xe3\x11\x05\xcd<\xe1Y\xf8\xd9r\x93\xff\x000\xefn`\x88\xacmIJ\x94\x12T\xc38$\x01W\xaa\x83\x1e\x16\xf4 \xc2I\xb2\xc6c\x99A\xcdNZ\xb3\xfdZ\x1f\xcc\xc0wK+\x9a\x92\xb3\xf0\xfd\x90\x91kf%\x80f\xfa\x1a~\x9a\x95\x80\xe8\x94\xa4%\xf3\x04\x85\xa5@\x12j\x90\xa5\x14\xd3\x80\x1cl\xf1`\x85\x00\x1d6\xd623\xf1fi|\xa0-\x95\x82IP*U4#\x87-_\x91\x8e\xa1\xd9M\xb73\x0e\x12\x10\xebH!\xc6gz\x17\xdd\xf4cV\x8a\xee\xc7\xd9R\x94\n\x14\xb7\x96\xa0\x1c\x06\x19\xb2\xb2\x93\xbdt\xd0\x8a\x03\xc8\xbd\xe2\xd9+g\'"2!(\x08\xa0 1 \xd9\xcb\xba\x9b\x9c+:qz\\@\xa6\xad"\xa8&\xb7\x7f\xc7\xa1x\xb4\xff\x00\xf9\x1b\x0e\nP\xb4MJ\x95\xab$\xa5\xb8\xbeg\xf2g\xe5\x16)\x1bQ\n\xb1\xbd\xb9\xbd\xa3\x87\xf6\x88\x89\x8b@H=\xe0!\xf9\xfbW\xf3\x83q\x93\xcc\xb4(&b\xd11 ebE\x00I\xd0\x87\x0f\x94\x10tTxb\xa6,\x86\xcf\xba\xee0\x06\x0c\xe4Gk\x9b\x8a\xca9\xc0\x18\x8d\xb6\x94\xd0\xb01\xc8{G\x88\x9d58u\xc9\x9d4\x85\xa9\x00\xa13\x14\xca\nP\xa1\x0f\xe4y\xc2\xbe\xcb\xcb\x95\x84\xcf>i$\x12D\xb4W.\xeb\xe6Q\x16%\xf46~a\x988\x82S\xa1\xfd\xbe\xfb\xe2r\xcc\xb0|A\xe3\xa1v\xb7\xb5\xc4\x0e\xed,\x14In\x82\xe6\xf7\xe1\xe7\x14Y\xeaT\xe9\xa0,MYp\xc9H\x01\xd3S\xe6m\xa1\xa3\xc2\x8d\xab\xda)s\xb7Ae\n\xa5MD\xd6\xc4\x8e7\xe4\xdc\xe2\x0c6\xd9\tb\xa4\xef\x01\xc4\x8c\xaa-cB\xd0\xaa\xa5M\'iB\xb1\xa0\xf8f*H\xda@\x1b:Wv{\xf3\xd2\xb4\x8b,\x9c@\x03!\x01A%\xc6z\x84%\xac\xe0\x82E\xdd*$T\xb0\x0e^,\xe4\xa5(`e\xcb\xccB\x89.Ar\xc3G$?\x93;\x08\x03\r\xb5\x9eR\x90\x9c\xaeK\xe6\x19\xb3(Q\xd1\xc1\xb5\xd2\xfa\xd8f&zP\x84\x84\xa9aJ\x05\xd3T\xee\x9c\xb9Z\xc0\x8f-:@\xf6To\x97\xb7\xaf8\xbc\tM\x81\xe1\xe4\\\xee\xb9\x00\xb9w \xd4\xc3\x19\xd3\xa5\xf7I;\xeaJ@\x04\x15ewPQgR\xb3T\x14\x96\t\x01\x92X\x98\x83\xbe\\\xe4\xcdZ|(c\x93%\x9fwO\x08f\x15\xe5\xce\x01\xc7\xe2\x02\x10\x84%\xc1,T\x93g\xab\x1b\x90\xe4\x1e\x02\xf6\xb1\x88v\x94\xd6\xee\x9e\x84$\x14\x94\xa4\xeaI\x17\x00\x96\xe3W\x82\x04\xb9\xaf~o\x11\xdaE\xc5\xdc\xb5\x8bU\xe8\xd4\xabd\xd4\x83\xe7b\xb3\x15\x90rM\x0c\x95 \x12J\xf3\x12\x08.jiRH\x14\x147\x85\xf8\x99\xb97j\x89\x8eB\xcaN\xed\x08 P\x90X\x83\xeck\xa4[Fx!\x14.\xd5&\x8e\x00\x00\x00\x05\x05\x9f\x89&\xf6\x85\xf8\xacX*v\x15#u6\xa0j;\xfa\xfe0@\x874\x80\x19\xc1\x08u\x1e\xaf\x93\x0c\xcb\xea\x01v9\xda\n\xc5\xe2\x1d\x19\x94\xce\xe0\x02I\xcc\xc9H\x19Y\xe8\xd7v\xb9\x80W-KVe;\x01D\xf0k\n\xe9Mth\x92L\xbb\x92\x92I\x1b\xb5\xb37\xb5\xef\x04\xa3\x82\r)Cc\xc0\xb5\x9c;y\x98\x9b\xec\xda\x02Q\xf3\x0f\x8a\x83Kv\xdav\x03F\x19\x04\xb1\xa0\xa7\xa9g\xad-\x10\xcc\xc1\x02\xe0\x1a\x7f~\xbc\xa1\xb4\xe7,\xb2\xc5!\x81\x14\x04\x91\x7f=^\xf5\xab\x98\x84\xc9z\x06`\xc0\x87\xa7\x01\xf4\xf1\xd4\xac\x88\x1c\xdc:\x14*:y\xda\xfe\xbb\xa2\xb5\x8d\xc1\x94\xa8\xb3\x94\xe8Hb\xcfG\x0eX\xb3R\xb1\xa4\xbc9bH\xa7\xcb\x9cY\xa6 1\xa8?\x81\xaf^\x10\x1e?\x02\xc3t\x83\xcb\xd2\x9c\xa1\x84\xcf{\xc5,\xff\x00\x87\x14\xf8\xa5\xd4]\xb3\xfc\xc2\xe9R\x0f\x12C\\\x08%\x19\xd2\x1d\xdc\x0e\x7f(\x87\r0\xa4\x14\x9b|\xa3tN\xd7Q\xe1\x11\xd2\xe4\xda\x12\x97:d\xb2\xe9&7\xfdby\xfaFA\xf9\x91\xf6\x91\xe9\xf9FG6\x11\xa47\xfa\xf9\xff\x00\xcd\xd2.)\xd93fPo\x06\xa1z\xb3P==9p\x86\x98^\xc9\xac2\xe6\xb0H\xab\x96?}\xad\xeb\tvv,%&a\x96\xa9B\x80\x92\xbb\xf0\x00ds\\\xbf\xde\x0c\xc6\xf6\x86|\xf9D\xa1\xc2w\x98\x8b\xdc\xe6=I\x07S\xc7ZU|\xb2\\w\xd38\xb2\xc5|VrRh\x123\xcc\xf4\x0c\xf1g\x13\x92\x90\x13$$\xa9 \x87\xa1\xcaK\x0c\xb5&\xa0\x00A\x15\xacs\xce\xdf\xed\t\xd2\xd6\x06bIz\xb6\x94\xb3}r\x10\xaaV*jV\xa2\x170(\x92\xd9\x14EE\xa8\x0b\x90*\xc3\xe8\x93\xda\x1d\xa0q\x12%\xf7\x83\xf6\xc8Q\n\xd0\xaa\xec\xa6\xd2\xc4\x11\xc5\xac\xe2\x19\x93\'\xe5\xac)\xdc~;\xf4\xca+\xe6a\xa7\x03\xc6\xe7>\xf2\x8d{3\xb6{\xc9S$L\xaa\xd03\xcb/R\x91\xe2\x97\xcf\x88\xe4\xfc"-\x9f\x87G|EV\xee\xf9t$\x97w\x0e\xa0\xd7\xb5\xe2\xbf.a\x94\xb11 8\xb3\xf4b)\xc9\xfda\xcfe\xb1\xaaJ\x94B\xcaJ\x81\n#P\xa2\t\x1d\x1c\x0bt\x86&\xa0\x00V,{1\x1c\x04\x83\xfa\x82\x83r\x08\xf3\x8b\x86\xc8\xc0\xad2\x84\xc6d0IsE\xb3\x03C\xe3\xbf6\xe5\x1b\xe2{K5)\t\xee{\xb0A\x00\x95\x13\x99\xb5\x03M8\xc39\x7f\xbaL\xc9\xeb\xa1\x00J\x96\x12\xe5\x91\x98f\xfe\x14\xb9W\xf3\x17\xa1g\x8c\xdb\x9b\x0b1\x96\xb4\x02\xed\x9d2\xd6|H\xa9\xb8\xf0\xd8\xf5\xf7\x8a\xd0\xca.{\xf2\xe5\xd3X\xb5\xf8\xa6\x18\x90\x9d\x90\x18;\xd3!\xbc\xb9,\xc5\xf7\xb6`\xc5rn\tg\xba\x9a\x95\x1c\xea%\x9e\xcfF=\n\x986\xbe\xad\xe62t\xc5\xcd\x0b\x99,\xa5H\x05*"\xc4\x1e<m\x16Um\x1c<\xd9&D\xcf\xd9\xad\xf5\xf8^\x9d\x14\x93b)\xd1\xc3D\x18\x9c4\xc9\x92SL\xcb\n\t$]\x85\nU\xc6\x95\n\xd4\x1a\xd6\xf2\n]\x08\xef\xb1H\xcd\x92K\xa7#\x0bvf \x8c\x1eu\x93\x95\x0bPA7\nu7\x1b\x01\xee!\x0e3\x0cfK\x13&\x9b\x9f\xd9\xa0Pd\x0fR\x03;\x9f\x91\xbb\x83\x16\xbcV\xc6\xcb*\\\xa5\x1f\xd9!JQ\x00:\xa6LZ\x8eP\xce\x1e\x8c\x1b\xf0\x80?W\xe6\xcd1k\x08aD\xb1&\x8c\xd6\r\xeaE\xa8\xf7\x82\xedl\xba\x87u&\x9ep\xde\x03\x0f\xf3\xa6\x84\xe4\x1bkp\xd3\x89\xe9|\x9c*\x97\xb1\xe6"PZ\xa5))S\xe46I"\xfaT\xd2\xcf\xc6\xd5\x80\xa6a\xd2A\n\x0c\xaa\xd0\x0b\x9d!\xfa\xd0H\x01\xfc:\xfd\xf6\xa9\x16~\x1e\x91\x161*\xa0VP\x05:\x93\xaf?-5\x8e|\xc2\xf4\x8dz$\x80\x9d\x925\xed\xb7\xfb\xd6*\xd3p\x85\xdc8\xad\xd3O\xa6\x81\xa7\xae`$\x9d\xeb\xde\xfe\xba\xc5\x93\x15\x85O\x89\x9a\x8e\xe0\x91Q\xd2\x14MA?\xcb\xf2\x86\x113j\xf0\x94\xec>\xcb\x94\x9288\xe8\xd0\xbd[K1\xa9\t \x01`\x91N\x809\xe7s\x1b\xce\xda\xa0\x91f\x0c\x19<\x07S\xe6z\x98\x87\x19\x86\xe1\xeb\x0bT\x86\x86R\x84*\xb1O7\x11\x89\x93\xe1~pn\'i\xac\x9a\x16\x10N\xc2\x90\xa5\xaa\x9eD\x9e\x0f\xc6\x9e\xb0\xac\'\xd6,\x9b\x1f\x0b\xba7\x82hMzZ\x82\xe6\xdf8\xe4\xe2\x94!\x84K\x02\x99\x98\x8cF\xd2\xcb\xb5}\x87X12\x94\x80\x874 \x96pX\x1a\x12\xda\x13\xee\xc2\'\x94\x10Ts&\x84P\n^\xceO\x91/\xf9\xc1\x18\\$\xc2L\xb2\x1c\x90.\xce\x00\xb3|\xb8\xd5\xb9D\xea\x98\x14\x00\xb1\x14`\x9a5\xdd\xf8\xbf\x11\xc3\x84W\xa9Q\xa9\x08\x19t\xdfc\xe7\x0b?F\x07x3\r\x0e\xad\xf7t\xfb\xa3c((\x80\xe5\xdb\xdc\xb3\xb7\xbc3\x9d\x87\x14\xca\x92\x90\xabs\x16%\xfa\x8b\\6\xb7\x8dU&\x89,\xd9h\xe6\xa0\x90\xdaG\x12\xb8\x1c\xc4\x82\x1f_V\xe8\xc4e\nU,&\x8dW\xf1tf&\x96\xebz\xc6\xb3\x12T\x01 17\x14~\xb0\xc6\\\x90\x1c+\xc2\x03\xd4\xb1.@\xa3\xdc\xd4\x16\xe0\x0cB\xb9D8M\xaa\xe3\x881=\xba\xc0\x15$e\xdec\xbd\xf5\x84X\xbc=\x0e\x8d\xafH\x1f\x0c\x14\xee\x94\x87\x02\xff\x00\x7fXo:E.,\xa0\xdc9z@\x02s+//A\x0c\xa1N#9\x8c\xc2\x010\x14\x8a\x1e\xfa\xfd\xe2~\xed\x7fo\xdb\xf3\x8c\x8d\xdcq\xf9\xc6Di\x10\xff\x00\x87\x8da\x97if\x92\xa4\xe8\x84\x02\x124\xa6\xeb\xfd\xc3\x93C\xae\xc6\x14L\x94\xb9J;\xc1\xcaO\x10x?\x02\xfe\xb0\x0fi0\xc52\xe5Z\xb9\x81\xe1x\x13\x04\x82\x9c\x8bC\xa5E\x83\xea\r\x85\xcbe\xebH\x11\x00%\xa1\x8c&\x0c\xe2\xf0e$\xb3\x92_\x7fL\x81\x1c\xf3\x8f1\x18f\x98s\xb2\x1f\xc2\xe1\xc6\xf5G\x89\xc3\x10]\xcd*\xf1\x1e3\x034\xcc2\xd6\xe6h\x7f\x15\xc3\x0e\xac\xec\x1e\xb7\xe6\xf0\xc3j\xce\x98&\xf8\x82\x88\xa2\x16\x82@cz\xaa\xa9rUCg"#\xc4\xe1\xc0XJ\xa62X\x02O\xc2@\xb1\x15p\x19\x83=\xa8\xf4\x11\xe0Z.\x82<\x00\x16}\x9d\xfb\xb4\xcbu\xdd\xa9H\xae\xe2p\xe0\xf9P\xf2\xfe\xf06\xcd\xfd\x9c\xca\xd8\xf1\x0f~\xa2\xfc\xfc\xe1\xac\xc4\x92\xa5\x07\x0c,\xd5\x05\xb8q\xb5\xfa\xc2\xccl\x92\xee\x1c\x11_\xa6\xb4\x1d\x05\xc6\xc9\xb1\x84\xa7$!b`\x15\x07^\x11\xd5v\x1c\xc4c&\xc9L\xd5\xa4&Z\x02h\xc0\x94\xcb\x04\x81\xcdG\xd6\xbd \xf9IX\x9ag\xcc\x98\x12T\x14\x94\xa1$\x17\xcc\x14\x9aeq\xdd\x81G\xf2\x16\x8eS\xb26\x8b5j\xf5\xe8?\xbd\xb9E\xb7f\xe2Uu(3=\xc0`\x1d\xeb\xd3HIr\xd4\x951\xa9\xbb\xfaynk\x98\xb3J\x931;iS\x06kZ\xef\xe7G\xa6T0V\xdc\xc1\x95\x8e\xfa]\x08 f\xa3\x10)^"\x8d]\x03i\x0f;\x1f\x88\x956I(Y\x13\x10\x92f\xcb`\x08U\x92\xc7T\xb0\x15\xe9k@\xf2p\xa8R\x12\x94\xac,3\xe6AtT\xd8\x1b3\xbf\x1e\x10,\xbd\x89\xdc\xce\xcf-E\x99D\xa4\x16S\x1b\xa7\xcf\xee\xf3\x8e\x15l\r\x85^\x9d\xfbF[\x1d.\\\xb9\xc7\xe4\x9a*\xa45\xb4c\xbe\xec\x19\xb4f\x868]\x9c\x89\xa4\xf7\x85m\xa0\x14\r\xa9j\xdc\x93Z\xc0\xbbCf\x8192\xa4\x94\x94\xacUKm\xda\xd6\xa6\xcc\x01$\xf0hc\xb0q=\xe6e\x10\x90\x80wX\xb8P\xd0\xbf\xc4\xfd,\xd06>z\x0c\xcc\xa1!\x9cx\xa8/\xa9$S\xa9\x10\x02\xa0\x05jm\xdf\xa4;\xf0\xb4\xcd\xdb\xfa\x8e\xc8\xabe\xc7.\x95\xde I\x86C\x14\xa2Z\x9d4\n\n\xca\xa2^\x85\x98\xa4\x01\xc1\xed\xad\xe1\x167\x0eR\xa4\x86!\x98\xd4\x17\xae\xb4\xadyCS5$\x9c\xe5YN\x89! &\xb9KeS\nY#NP&\xd2\x9f\x9dI.\xb5\x00\x9c\xa9\xccj\x00r\xda\xbaA\'\xab\xe9\x13\np\xe2\xfc\x00\x8d\x1a\x01\x14\xad\xb5\'\xad3\xca\x9a\x88]\xb4\x92S,9\n\x04\x03\xa5\x1cX\xea\xe3\x84%B\x08\x05\xb5\xf5\x1a\xc3}\xad\x89+P+\x01\x00_*@\x01\x85(\xe0p\xebz\x98Y\x88 \r\xc5\\o\x06!\x8b\xdb\xda\x18H\xd2 \xa1`GC\x9e\xfbq\x1c-\x0b\x96\x1c\xd7\x89\xcc\x1e\x16\xe2\xe4p\x86D8\xcd\xc0\xc4\n\x10\xda\x14Eb\xa2|\xa4\xac1\x85\xd2R\n\x92\x1a\xe6.\xb8,\x15\x01\x06\xacn\x0b\x00\x18\x0b\x02\xf7 0\xa7(\xab\xc9\x94\xd3\x12.\xef\xd7\xc3H\xba\xe0\xb0*B\xd3\xbcF\xf09\x92\xabQ*\x15\xd1L\xdd\x0c\x0b\x16\xbb4\x1f\xe12\xf6\x02\xdc\xd5\xdb\xa0\xfb\xbf\xde$T\xa5d\x0b\x05\xcd\x89\x02\x809bH\xbb\xf1!\xf4\x8d\xd3#*\xcfx\x8b\xd4\xa4\x1b8\x05\x9e\xa4\\\x16?\xd8\xc9\x984&a \x91,\xe6\xc9\x98\xe8\x0e\xe8,\xf5\xb5\x1b[\xeb\x19\x84\x91\x99L\xc0\\\x95;n\xf3zQ\x89~\xa2\x12\x06\xb4\xbc[m\x86\'*\xee\xbd\xeb\xb8\xb8-[\x01j\xc1\'\x04\xf9\xb2\xd5\x81\xb5i\xc4~=#\xd9\xd8g\xcc@ T\x87\xf8C\xd1\xfd@\x83S,\x102\xa4\xd1\x8b*\x86\xa2\xf4\xb1\xa816\'\n\xbc\x82nW@%.\x14\x0eSK\xb1\xa3\xd4\x00n\xfd#\x83\xcf\x84\rS*\x1f=[\xef\xddY\xecRMb\x96\xa9\xca\x12\x01f6\xa8\xe6\xc6\x80\xf0h\xd3\xb9\xee\xc1}C\xdc3\x11O7\xf9AJ\x04\xe6#\xe1 \xbe\xb7\x0c|\x8b\x0f1\x01b\xb1\x19\xafS\xf5X\x91x\x8e\xceOA\xbe\xaf\xf6\xd6\x02\xc5\xe0H(\xa8\xaf\xce\xa1\xba\x82\x18\x8f\x9c#\xc6\xa0\x02T\xd6\xfa\xaf\x18{\x8b\x9aU\xd4U\xea\xe4\xeaI5rj\xfc^\x13\xed2\xc8v\xfa<y\xc3r\rCEv-\x07e\xd5~\xde\x02\xefW\xcb\xd4~1\xecA\xdeK\xfb\x1e\xf1\x90\xcb\x18\xac\xda^\xa3\xca:^\xdc@\x9d-\x05$\x1e\xec\xa5\xc8&\xa4\x81@\xe1\xc1\xea\xd61\xe6)Bl\x95\xaaZ@T\xb5Wt\x05.Y\xf0\x9c\xa9\x19II,Jj\xcas\xc4I\xb46\xc7|f\x89h\x97-\x0bU%\x89I\xccC\xd1\x95\x94\xd5\xd9\xc0P\xb0h\x8fg\x85a\xd6t\xee\xd4\xb0\xa5\x02H\xab36\xae\t\x1cX8\x84SR\xc0\xbe\xa6/\xe5HL\x89`$3\x17\x03\x8dH\xdf\xd4X\xe4\x04\x01\x8f\xc2K\xc8\x92\x82J\x81e\x00\x0b.\xc72FT\xb2MFSb/Q\x01,\xa4\xabw2%\xd4\xe5;\xdb\xdc\t\x0c[@X\xd8R\x1f\xec\xd4\xf7\xcaQ\t3?k\x9b 4Rl4\x04]\x81q\xad\x04\x03\x81\xc3\xfe\xd2d\xb0\x99j$-\xca\x83\xd0\n\x84\xa9\xd8\x1a8#\xdc\x16<\xa8\xef\xd2\x18{\x87\xa8\xe9\x9f\xb7\xab\x1b\xc2\xe9\xd8P\xb2\xb5\xa0\x13(Q\xc9\xf0\xb8SxC\x13\xcbV>J12Ckj\x9e-\xa5\x1cs\x8b\x1a\xe5,H\xce\x00\xee\xb3\x10\xa2(I:,\x03j\x12\t\x1cX\xde\x03\xc6afwUFTQ>\x16$\xb3\x82A>"5j\x86\xbbD\x92\xb8\x04\xc9o}H\xb8\xc8w\xa5\x1a+{?bM\x99\xbd,\xa2\xecAP\x04\x1f8\xb4`v<\xc4d\x06t\x92If\nS\x9e \xb2Hnv\x8a\xdc\xf9kJ\xf7\n\xa5)\xc5A)a\xcf^l`\x9cWh\x17-N\x96T\xc2\x00~C\xad\x7f\x12L2\xbd\xa5\xb3F^l\xf9\xb8I\x9b\x08=\x9e\x9d"\xcb\x83\xc6L\xc2\xa9x|\x85`\xa8dK\x10\xca,\x00\xa8v\xf5\xa8\xe6\xf1l\x90\xb4IJN%yB\xc1!\xd2\xa6!\xaa\x97\x00\x80k@\xf5jD\n\x90$/\x07,\x84\xaal\xc5\x9c\xcbj\x80\x84\xe6Sk\x975\x00v\x01\xa2\xee\xa9\x12\xd3 \xe7@X7\n\x0e\xe4\xf5\x84\x8a\x01P^C\xf6\x85\x93$\x94\x8a\xbb\xd2\x13\xab\x00%\xca\x05#+\x87m@!\xdb\xca\xdeQZ\x98\x94\x12\x1c\x90_y\xec\xce,\xde\xbe^Qa\xc6m"\xa5\xd6\x9d^\x15\xcaR\xb3\x85\xa1!E\xe8\x92\xc4\xa8\xb1d\xe5%\xd4:\x07\xd4TQb\x01>\x1c\xb7?H\xd3`\xd0\xa9Hc\xea\xdc\xb3\xef\xa8iZB\xf2\xf7\tYr\x19!u\x1cC*\xfa\xd4\x1fz$\xc4N\x96\x16XfI\xb3\xdd\xb9\xb6\xba|\xa1\xde\xd9\xda3;\xd0\x82\xbc\x81)\x05)\x0c\xc38\n9\x8f\x89\xcee\x1eN\x00g\x8a\xbe.rR\x18\x04\x96\xb2\x93C~w\xe1k\x181\x0fOf\xfc\xf9\xc5\x8c\x94\x93R\xf5\x02\xc4\xfa\xd3L\x9c\xd4\x82K\x03\x10\xe3RTH4\xeb\xc9\xd8r\xe1\x0bY\x8b_\x91\xe6\xde\xb0\xcf\x13=J\x943\xd9\xcb\x1b\xb8\xd5$\xb9fpk\xc4\xf1\x85x\x80\x90wk\x7fM-\xac\x15\x03(\xe4\xc4\x92)\xe8\xe1\xc7\x97\x95\xef\xbc\x91\xf1r\xd8\x9a\x86<\x08\xd6\x05JH,i\xa7\xbc\x1b\xba\xcc\xa3\xae\xb5\rK5^\xfe\xd0*Et\xa3\xb74\xf0\xe3\xca\x1aA\xa4V\xce\x1e-\xfd\xf6"2\xc1iQ\xd1I\xaf\xb4^vv\x1eb\xe6"PP\xdfP\x00\xb9\x01\xd4h\x1fAkp\x8a\\\xc4\xd2\xbe\xdcxP\xc5\xefd\xe2\x12%\x12\xa4\xe6J\x8aJWZ0P\xca\x08\xa0;\xc0\xf9\x0ep\xb6%\x88\x04\xef\xef\xda\x1b\xc2\x92\x82\xa6\xa9-M\xe5\xfd9A;?\x05\xfbE\xa2a\xc8\x00]T\x0b\x0c\x97\x14\xad\xbc\xf9C)+\x95&B\xd4Oz\xa2\xbc\xa1iv\x01\x81c\x99 \xb5>\\av\x03\x16\n\xd9J\xca2M\xa6\x85J\x96\xa0\x00\x0e\xceM\x07\x94{7\x0712\\JP\x96\xd9\x94r\x90\rK(\xd1\xa9\x98\x87\xd4\x13\xc6\x02\x85\x14\x87H\xadG\xef\xce\r5;D\x05\x9b\xec\xbd\x86\xb9\xf2\x14\x04\xd5\xa8\xd5\x0fv\\\x84\xa1%x\x89\xa0 \x80\x84\x90\xcaQ`\x85$&\xec\x18\x83\x98\x03Jj\x04.\xc3J\xcb:l\xa7L\xc7B\xf3\xad*t\xaa^B\xa7\xb6\x84%C\x98maF\'j(&PR\xc8\x12\xfc\x01E\x80\xab\x96s\xc6\xaf\xe5\xc2\x06\x9d\xb4\xa5\x94\x84\xa5\x9c)G0\xe0\xac\xbb\xb4\xb0\x0cO\xfec\x1c\n\x1e\x10\x91D\xd7\xee4\xe9\xae\xb0?\x92A;F\xaa\xec\x1dz\x9a\x9aY\xcc3&\x96W:k\xc5\xdb\xd5\xba\xb7(\xf2V\x1d)T\x95L,\x952\x89g\xdd\x0b#5.\x18\x1f\xce6J\x86B\x90\x1dEA\x8f\x00\x1e\x8d\xcd\xfd\xb9\xc4\xb8m\x9d\x98\x14\x92\xdb\xa1\xcb?\x88\xd3\xc9\x80\xfe\xa8\x94\x90\xe5\x8c\x07\xe2X\xc1"QP\xcc\xb0\x1a\xbf\xa3\x07<\xb40\x1a\x14\x16\x14BC\xac\xee\x87\xb2jO\xe1\xe5\x08{A\xba\x1bR\xddy\xfdt\x8b\x86\x0b\x0b\xdc\xa9i\x0cs%\x83\x8b$\x97\xf6f~\xb1\\\xdb\x18Ebf\x04J\t\xdcp\xa5\x15\x10\x1c\xb5\x1a\xbb\xc3V\x14xb@\xf1>Q_\x8a\xc5!r\\Q\xfd\xf5\x8a\xa4dX\xff\x00\xe9\t\xdfnO\xf5+\xfe\xd8\xf2\x1d\xdbN\xb1W\xfa\x94k\x17\x1e\xcd\xff\x00\x9b\x93\xfe\xaa?\xdc M\x97\xfb\xe3\xd7\xfeI\x8c\x8c\x84%\xe5\xc7\xed\x1b)\xdfL\xcf\xe9\x1e\xaa\x86]\x83\xb4\xff\x00\xe4\xfc`m\x95\xfb\xe4\xff\x00\xa9\xf7*=\x8c\x8e.\xc8\xe3\xef\x00\x9b\xfcY\xdf\xdb\xfe1!\xff\x00&\xaf\xe4\xff\x00\xe5\x10\x97\x13\xe1G\xf2\xa7\xfeQ\x91\x90$\xdd=\xe6`\xc8\xba\xbf\xad\x7f\xe4`]\xb5\xfb\xe9\xbdf\xff\x00\xca*\x83\xfc\xc2?\x9d\x1f1\x19\x19\x168[\x9e\x020\xf8\x8f\xe3\x7fj?\xc4Gc\xed\x0f\xfe%\xb3\xbaN\xff\x00l]1\xdf\xb9=G\xccFFB\x8a\xfa\x07\xf4\xfb\xaa\x1c\xc2}(\xfe\xbf\xb4W\xb6\xef\x89]\x07\xc8BlU\xcf\xfa\x8a\xff\x00r\xa3#!9\x9f\xc4Th\xf0?B8\x1fA\x0b;]\xfes\x11\xfe\xac\xcf\xf7\x98K\xf0/\xca=\x8c\x82+\xeaW\x1f\xfc\xa1\xc5\x7f\t?\xdb\xed\x19\x86\xfd\xcc\xdf\xe4\x1f\xfb\x92\xa1L\xcb}p\x8c\x8c\x86\xc5\x87y\x98^o\xd4\xae_\xe2\x98\xdfj\xfe\xf0\xff\x00?\xdd\x03/\xc5\xe5\xff\x00(\xc8\xc8*-\x08\xce\xfa\x8f\x11\xe9\x1a\xab\xf7c\xca.{\x07\xff\x00\x0e_\xfa\xb2\xfeS## s\x7f\x86y\xfa\x18,\xaf\xe2\x8e\t\xff\x001\x11\xa6\xea\xfa\xd2\x1bc\xbf\xcb\xa3\xaf\xde\xb8\xc8\xc8L\xfd+\xe1\x16K\xbax\xfbE#o\xfe\xfd_\xca>P\xb7\xe2O\xf3\x08\xc8\xc8\xb3G\xd08{G\xcd\xb1_\xfe\xd5\xff\x00\xdc?\xe5\x16l\x16\x9fZ\xc5\x93\x0f\xe2?\xca\x9f\xf6\xa2=\x8c\x8a\xf9W<"\xff\x00\xe3\x1fJx\xc0\x98\xaf\xdf\x0e\x8a\xff\x00\x94&\xc0]\x7f\xea\xcc\xff\x00\xdd\x9b\x19\x19\r\xca\xfa\x0f\x18\xaa\x9b\xfc$p\xf7\x83c##"0\xac\x7f\xff\xd9'


In [343]:
with open('b.txt', 'wb') as f:
    f.write(b'\x04\x04\x04\x04\x04')

In [345]:
with open('b.txt', 'rb') as f:
    a = f.read()
    print(a)

b'\x04\x04\x04\x04\x04'


In [346]:
print(b'10010110')

b'10010110'


'0b1111011'

In [351]:
import pickle

In [364]:
import pickle

# 저장할 객체 생성
data = a
# 객체를 pickle 파일로 저장하기
with open('test.npy', 'wb') as file:
    pickle.dump(data, file)

# pickle 파일에서 객체 불러오기
with open('test.npy', 'rb') as file:
    data_loaded = pickle.load(file)

# 로드된 객체 출력
print(data_loaded)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
