In [5]:
class A:
    __x= 1 # encapsulasion # magling(엉망진창으로 만들다)

In [6]:
dir(A)

['_A__x',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']

In [9]:
A._A__x

1

In [16]:
# .을 할때 어떤 것을 실행하는지 결정하는 것이 discripter이다.

In [207]:
# 아 놓침.. 
class D:
    x = 1
    def __get__(self, obj, objtype):
        print('get')
    def __set__(self,t):
        print('set')
    def x(self):
        print('x')

In [208]:
d = D()

In [209]:
d.x

<bound method D.x of <__main__.D object at 0x1538a7750>>

In [18]:
a = np.array([1,2,3,4])
a.shape # __get__ (디스크립터)가 만들어져 있음
a.shape = (2,2) # __set__ (디스크립터)을 재정의해 놓아서 값이 변경되면 인스턴스의 구조가 변경된다.
vars(a)
# 텐서는 없다.
# 위의 것을 알아야 서드 파티 개발자들이 쓴 코드를 알수 있다.

# 디스크립터를 만드는 방법은 3가지이다.
    # 올드스타일 (위에 것)
    # 뉴스타일1 (좀더 우아하다)
    # 뉴스타일2 (데코레이터 프로퍼티를 사용한다.)

NameError: name 'np' is not defined

In [ ]:
# 자신이 바뀔수 있는것: 뮤터블과 디스크립터

In [54]:
# 뉴스타일1 (좀더 우아하다)
class D:
    def __init__(self):
        self.__x = 0  # set이 실행된다.
    def g(self):
        return self.__x # 무한 호출 되어 에러 난다. 
    def s(self,t):
        print('set')
        self.__x = t
    x = property(g,s) #함수를 인자로 받는 하이어오더 방식
    

In [55]:
d = D()

In [56]:
d.x = 5

set


In [57]:
d.x # __x 대신에 x를 반환해 준다. 

5

In [58]:
d.x  # 값을 보호한다. 안 바뀐다. encapsulation

5

In [94]:
# 뉴스타일2 (데코레이터 프로퍼티 사용)
class E:
    def __init__(self,x):
        self.__xx=x

    @property
    def x(self):
        return self.__xx

    @x.setter
    def x(self,x):
        print('set')
        self.__x = x


In [95]:
d = E(3)

In [96]:
d.x

3

In [97]:
# .을 붙이는 순간 다양하게 실행된다.
# 존재를 알고 친해지면 된다. 
# 웹 프로그래밍 -> 외우는 양이 적다
# 파이썬 2년은 해야 한다. 

In [99]:
import numpy as np
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [ ]:
# 넘파이는 팩토리 메소드를 많이 지원
# alias array
# 분석 포기하자

In [ ]:
# 분석들어가면 힘들 것이다. 

In [ ]:
# 응용이 가능해지려면, 많은 노력을 해야한다. 
# 익숙해지려면, 
# 뒤쳐짐을 알아라. 이미 늦었다.

In [ ]:
# 데이터 프레임워크는 함수형프로그래밍이 중요하고
# 텐서플로우, 인공지능은 함수형프로그래밍과 함께 파이썬 문법을 잘 알아야한다.

In [ ]:
# 1년 AS 기간

In [100]:
# 텐서플로우 variable vs ??

In [101]:
a = np.array([1,2,3,4])

In [102]:
a.ndim = 3  # 3차원 만드는 방법이 너무 많아서 제한해놓았다.

AttributeError: attribute 'ndim' of 'numpy.ndarray' objects is not writable

In [103]:
# numpy shape 과 dtype 외우기

In [104]:
# 칼럼 하나가 넘파이 하나??

In [105]:
# numpy를 만드는 팩토리 메서드가 여러개이다

In [190]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [109]:
a = np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [111]:
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [114]:
a = np.triu((3,4)) # 상삼각행렬
a

array([[3, 4],
       [0, 4]])

In [116]:
a = np.tril((3,4))  # 하삼각행렬
a

array([[3, 0],
       [3, 4]])

In [ ]:
# 선형대수 개념만 알고 있으면, 선형대수를 활용한 계산을 numpy를 사용해서 할수 있다.
# 딥러닝 선형대수 2주면 된다. (?)

In [124]:
# 행렬 연산에 사이즈가 중요하다.
a = np.ndarray((3,4))
a
b = np.ones_like(a)
b 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
## tensorflow
## 텐서도 펙토리 메서드가 있다.
## 빨리 찾으면 된다.

In [128]:
np.lookfor('identity')

Search results for 'identity'
-----------------------------
numpy.identity
    Return the identity array.
numpy.frompyfunc
    Takes an arbitrary Python function and returns a NumPy ufunc.
numpy.ma.identity
    Return the identity array.
numpy.matlib.identity
    Returns the square identity matrix of given size.
numpy.polynomial.Hermite.identity
    Identity function.
numpy.polynomial.HermiteE.identity
    Identity function.
numpy.polynomial.Laguerre.identity
    Identity function.
numpy.polynomial.Legendre.identity
    Identity function.
numpy.polynomial.Chebyshev.identity
    Identity function.
numpy.polynomial.Polynomial.identity
    Identity function.
numpy.any
    Test whether any array element along a given axis evaluates to True.
numpy.eye
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
numpy.poly
    Find the coefficients of a polynomial with the given sequence of roots.
numpy.vectorize
    vectorize(pyfunc=np._NoValue, otypes=None, doc=None, excluded=None

In [129]:
np.info('tril')

     *** Found in numpy ***
Lower triangle of an array.

Return a copy of an array with elements above the `k`-th diagonal zeroed.
For arrays with ``ndim`` exceeding 2, `tril` will apply to the final two
axes.

Parameters
----------
m : array_like, shape (..., M, N)
    Input array.
k : int, optional
    Diagonal above which to zero elements.  `k = 0` (the default) is the
    main diagonal, `k < 0` is below it and `k > 0` is above.

Returns
-------
tril : ndarray, shape (..., M, N)
    Lower triangle of `m`, of same shape and data-type as `m`.

See Also
--------
triu : same thing, only for the upper triangle

Examples
--------
>>> np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

>>> np.tril(np.arange(3*4*5).reshape(3, 4, 5))
array([[[ 0,  0,  0,  0,  0],
        [ 5,  6,  0,  0,  0],
        [10, 11, 12,  0,  0],
        [15, 16, 17, 18,  0]],
       [[20,  0,  0,  0,  0],
        [25, 26,  0,  0,  0

In [130]:
# 중요한 것은 수학적 컨셉이다. => 2년 과정 해야한다.

In [ ]:
# absolute basic for beginners

In [145]:
class A:
    def __str__(self):
        return 'asdf'
    def __repr__(self):
        return 'qwer'

In [146]:
a = A()

In [147]:
a

qwer

In [148]:
print(a)

asdf


In [149]:
# 넘파이 조심 할것
a = np.array([1,2,3,4]) 
a, print(a) # repr, __str__

[1 2 3 4]


(array([1, 2, 3, 4]), None)

In [150]:
import inspect 

In [151]:
inspect.getsource(A)  # 예쁘게 출력 안해줌. 

OSError: source code not available

In [152]:
from sklearn.datasets import load_iris

In [153]:
data = load_iris()

In [154]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [ ]:
a = tf.constant([1,2,3,4])

In [ ]:
import pprint # 더 예쁘게 찍어준다.

In [155]:
import this  # Beautiful is better than ugly. => 파이썬도 외모지상주의

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [156]:
# 파이썬의 ...은 객체다.

In [157]:
# 텐서플로우는 혼돈스러운 부분을 잠아주고 베이직을 잡아준다.
# 텐서플로우는 array + 수학적 컨셉

In [ ]:
# 벡터라이즈
# ******엘리멘트 와이즈(elementwise)*****

In [158]:
a = np.array([1,2,3]) # 넘파이 데이터로 변환할 때시간이 좀 걸려서, 작은 데이터는 파이썬이 더 빠른 경우가 있다
                      # 큰 데이터는 넘파이가 파이썬보다 약 20배 빠름
b = np.array([1,2,3]) # 오퍼레이터 오버로딩

In [ ]:
class X:
    def __add__(se)

# 함수형 페러다임에는 연산자가 없다.

In [159]:
a + b

array([2, 4, 6])

In [160]:
a * b

array([1, 4, 9])

In [ ]:
# 내적 외적 안알려줌. 알아서 찾아봐라

In [161]:
from operator import add # 함수다.
                         # 넘파이도 대응하는 함수가 있다.

In [ ]:
# 내적하는 방법
np.dot(a,b) # 각각 곱한것을 더한 것이 내적이다.
            # 벡터를 스칼라로 변환해준다.
            # 선형대수에서 가장 많이 사용하는 연산이다. 

In [ ]:
# 외적하는 방법
np

In [ ]:
a.dot(b)

In [ ]:
연산자 > 함수 or 메소드   (명확하게 알고 있기)

In [ ]:
# 데코레이터를 연산자를 사용할 수 있게 해주었다. 넘파이만을 위해서
a@b   # shape에 따라서 다르게 행동한다.
      # 행렬곱
      # shape에 대한 다형성

In [168]:
aa = np.array([[1,2],[3,4]])
bb = np.array([[1,2],[3,4]])
aa@bb,\
aa.dot(bb)

(array([[ 7, 10],
        [15, 22]]),
 array([[ 7, 10],
        [15, 22]]))

In [ ]:
# 효율성의 시대.. 어떻게 효율을 끌어올리지? 

In [169]:
# 뼈대 잡는 중

In [ ]:
# 연산을 편리하게 해준다 - 브로드캐스팅 - 사이즈가 안 맞아도 연산을 할 수 있게해준다
# Broadcasting
    # copy tech를 이용
    # 내부적으로 최적화된 방식으로 연산

In [170]:
aa = np.array([[1,2],[3,4]])
aa + 1

array([[2, 3],
       [4, 5]])

In [171]:
aa + np.array([[1,2]])

array([[2, 4],
       [4, 6]])

In [172]:
aa + np.array([[1],[2]])

array([[2, 3],
       [5, 6]])

In [173]:
aa + np.array([[1,2,3]]) # 브로드캐스팅 불가 에러

ValueError: operands could not be broadcast together with shapes (2,2) (1,3) 

In [ ]:
# 텐서플로우에도 브로드캐스팅 나온다.

In [ ]:
import tensorflow as tf
tf.constant([[1,2]]) + tf.constant([[1],[2]])
# 텐서는 넘파이보다 쉽다.
# 넘파이에서 어려운 것 다 제거 했다.
# 넘파이는 모든 분야에 적용가능하지만, 텐서는 인공지능 용으로만 만들었기 때문
# 텐서는 선형대수 내용만, 텐서플로우와 다르다
# 텐서만 하는데, 데이터 분석은 넘파이를 더 많이 사용한다.

# 넘파이에서의 특별한 개념들을 정리했다. 지금

In [ ]:
# 모양 바꾸는것이 중요하다.
# 브로드캐스팅이 있어도 연산이 안되는 경우가 있다. -> 이걸 해결하는것이 중점

In [176]:
# 인덱싱과 슬라이싱의 추가 요법 5개 -> 암기 (카드 만들기)
a = np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [177]:
a[0][2]

2

In [178]:
a[0,2] # 추가1

2

In [179]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [180]:
a[0,1,2]

6

In [ ]:
# 한눈에 보는 연습하기 

In [181]:
import seaborn as sns

In [183]:
tips = sns.load_dataset('tips')
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [184]:
tips.iloc[2,1] = 100 # 데이터 분석하는 사람들에게 정말 중요하다. 
tips

total_bill     tip     sex smoker   day    time  size
0         16.99    1.01  Female     No   Sun  Dinner     2
1         10.34    1.66    Male     No   Sun  Dinner     3
2         21.01  100.00    Male     No   Sun  Dinner     3
3         23.68    3.31    Male     No   Sun  Dinner     2
4         24.59    3.61  Female     No   Sun  Dinner     4
..          ...     ...     ...    ...   ...     ...   ...
239       29.03    5.92    Male     No   Sat  Dinner     3
240       27.18    2.00  Female    Yes   Sat  Dinner     2
241       22.67    2.00    Male    Yes   Sat  Dinner     2
242       17.82    1.75    Male     No   Sat  Dinner     2
243       18.78    3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [185]:
# 컴마 인덱싱
# boolean indexing

In [ ]:
b = np.array([1,2,3,4])

In [186]:
b > 2  # 브로드캐스팅

array([False, False,  True])

In [187]:
b[b>2]  

array([3])

In [189]:
tips[tips.sex=='Male']  # 정말 유용하다. 분석하는 사람들은 절대 모르면 안된다.

total_bill     tip   sex smoker  day    time  size
1         10.34    1.66  Male     No  Sun  Dinner     3
2         21.01  100.00  Male     No  Sun  Dinner     3
3         23.68    3.31  Male     No  Sun  Dinner     2
5         25.29    4.71  Male     No  Sun  Dinner     4
6          8.77    2.00  Male     No  Sun  Dinner     2
..          ...     ...   ...    ...  ...     ...   ...
236       12.60    1.00  Male    Yes  Sat  Dinner     2
237       32.83    1.17  Male    Yes  Sat  Dinner     2
239       29.03    5.92  Male     No  Sat  Dinner     3
241       22.67    2.00  Male    Yes  Sat  Dinner     2
242       17.82    1.75  Male     No  Sat  Dinner     2

[157 rows x 7 columns]

In [ ]:
# map,filter,reduce => 불린인덱싱은 필터이다.                