In [1]:
# 넘파이

In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([1,2,3,])

In [3]:
dir(a) # __array__가 있으면, 넘파이와 연동이 된다.
       # __ufunc__가 있으면 ufunc에 적용가능

['OVERLOADABLE_OPERATORS',
 '_USE_EQUALITY',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__complex__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__tf_tensor__',
 '__tf_tra

In [4]:
from scipy import stats

In [5]:
dir(stats)

['BootstrapMethod',
 'CensoredData',
 'ConstantInputWarning',
 'Covariance',
 'DegenerateDataWarning',
 'FitError',
 'MonteCarloMethod',
 'NearConstantInputWarning',
 'PermutationMethod',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_ansari_swilk_statistics',
 '_axis_nan_policy',
 '_biasedurn',
 '_binned_statistic',
 '_binomtest',
 '_boost',
 '_bws_test',
 '_censored_data',
 '_common',
 '_constants',
 '_continuous_distns',
 '_covariance',
 '_crosstab',
 '_discrete_distns',
 '_distn_infrastructure',
 '_distr_params',
 '_entropy',
 '_fit',
 '_hypotests',
 '_kde',
 '_ksstats',
 '_levy_stable',
 '_mannwhitneyu',
 '_morestats',
 '_mstats_basic',
 '_mstats_extras',
 '_multicomp',
 '_multivariate',
 '_mvn',
 '_odds_ratio',
 '_page_trend_test',
 '_qmc',
 '_qmc_cy',
 '_qmvnt',
 '_rcont',
 '_relative_risk',
 '_resampling',
 '_rvs_sampling',
 '_sampling',
 '_sensitivity_analysis',
 '_sobol',
 '_stats',

In [6]:
stats.beta

AttributeError: module 'scipy.stats' has no attribute 'deta'

In [5]:
import numpy as np

In [12]:
a = np.arange(24)

In [13]:
b = a.reshape(2,3,4)
# b = a.reshape((2,3,4)) 원래는이렇게 넣는게 맞다.
# np.reshape(a,(2,3,4)) 이건 안된다.

In [14]:
b[0,0,0] = 200  # 대입할 때 항상 조심해야한다.
                # shallow.copy, deep.copy

In [15]:
a,b

(array([200,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]),
 array([[[200,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],
 
        [[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]]]))

In [ ]:
b = a.reshape(2,3,4)

In [ ]:
# shape을 바꾸려면, element 의 수가 같아야 한다.
# 그런데 음수를 넣으면 자동으로 맞춰준다. 단 음수는 하나만 넣을 수 있다.

In [16]:
b = a.reshape(2,3,-1)

In [17]:
b

array([[[200,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [18]:
b = a.reshape(2,3,-2)

In [19]:
b

array([[[200,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [20]:
a.reshape(2,-1,-1)

ValueError: can only specify one unknown dimension

In [ ]:
# 2차원 데이터를 1차원으로 바꾸는 방법 
# 1. 모델 밖에서 바꾸기
# 2. 모델 안에서 바꾸기 - Flatten

In [21]:
# resize

In [222]:
a = np.arange(24)

In [223]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [235]:
a.resize((3,10), refcheck=False)  # 자기자신이 바뀐다.

In [236]:
a  # 자연어의 길이 문장 길이를 맞춰줄 때 많이 사용한다. -> " 제로 패딩 "

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23,  0,  0,  0,  0,  0,  0]])

In [226]:
# tf.기본텍스트 분류 -> 제로 패딩

In [227]:
b = a.flatten()

In [232]:
a,b

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23,  0,  0,  0,  0,  0,  0]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23,  0,  0,  0,  0,  0,  0]))

In [36]:
b[0] = 100  # copy technique 가 숨겨져 있다. -> 자연어에서 많이 쓴다. 

In [37]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23,  0,  0,  0,  0,  0,  0]])

In [237]:
b = a.ravel() # view technique
          # Volero = View  -> 영상에서 많이쓴다.

In [238]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  0,  0,  0,  0,  0,  0])

In [40]:
aa = np.arange(6).reshape(2,3)

In [41]:
aa

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
aa[None]  # 2,3 -> 1,2,3

array([[[0, 1, 2],
        [3, 4, 5]]])

In [44]:
aa[:,None] 

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [45]:
aa[:,:,None] # 

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [46]:
aa[...,None] 

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [47]:
np.newaxis is None => None을 대신 할 수이 있다.

True

In [ ]:
# Einsum - 수학에 연관 되어있다. 

In [48]:
from collections import namedtuple

In [51]:
Point = namedtuple('Point',['x','y'])  팩토리 메서드? 

In [52]:
p1 = Point(x=3, y=4)

In [53]:
dir(Point)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__match_args__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_asdict',
 '_field_defaults',
 '_fields',
 '_make',
 '_replace',
 'count',
 'index',
 'x',
 'y']

In [58]:
xxx = np.ma.array([1,2,3], mask=[True, False, True])

In [60]:
xxx.count()  # 가려진 데이터 수

1

In [61]:
# 데이터 처리 딴 생각하면서도 할 수 있게 해야한다.
# 시키면 바로 결과물이 튀어나와야한다.
# 생각을 한다는 것은 바로 튀어나와야한다.
# 생각없이 할 수 있어야한다

In [62]:
xxx = np.matrix([[1,2],[3,4]]) # 학교에서는 긴것을 알려준다.

In [63]:
xxx

matrix([[1, 2],
        [3, 4]])

In [64]:
xxx = np.mat([[1,2],[3,4]])

In [65]:
xxx

matrix([[1, 2],
        [3, 4]])

In [66]:
xxx*xxx  # operator overloading # 매트릭스에서 곱은 행렬곱

matrix([[ 7, 10],
        [15, 22]])

In [68]:
# 함수형 프로그래밍과 어레이 프로그래밍의 공통점은, 동시에 여러 데이터 처리에 최적화가 되어있다.
# Neural Network는 FuncP + ArrayP의 융합

In [70]:
# 데이터가 많을 때, 여러 데이터를 하나의 값으로 표현하는 것이 중요하다.
# Reducer = 여러개의 값을 하나의 값으로 줄인것. 평균, 중간값, 시그마

In [ ]:
# Reducer 작동법
1+2+3+4+5
 3
   6
    10
      15

In [72]:
from functools import reduce

In [73]:
reduce(lambda x,y:x+y, [1,2,3,4,5])  # 인자를 뽑을 때 속도가 느리다
                                     # 팩토리얼 계산 할 때, reduce 쓸 수 있다.

# map: 동시에 데이터를 다른 형태로 바꿀 때
# fiilter: 데이터를 걸려낼 때
# reduce: 데이터를 하나로 축약할 때
# 빠르다는 장점이 있다. 

# 넘파이의 행렬은 메모리상에서 연속된 1차원이다.

15

In [103]:
a = np.arange(6).reshape(2,3)

In [104]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [105]:
a.dtype

dtype('int64')

In [106]:
a.strides(12,4)  # 12: 메모리의 보폭, # 

TypeError: 'tuple' object is not callable

In [81]:
a.sum(axis=0) # 초강속으로 계산할 수 있다. 
              # 행마다 결과를 내라 
              # reduce, demention reduction 
              # 선형대수

array([3, 5, 7])

In [ ]:
a.sum(axis=1) # 초강속으로 계산할 수 있다. # 열마다 결과를 내라  == 차원 축소

In [82]:
# 3차원
aa = np.arange(24).reshape(2,3,4)

In [83]:
aa

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [84]:
aa.sum(axis=None)

276

In [85]:
차원 축소, 차원 축소 리덕션

SyntaxError: invalid syntax (2945500782.py, line 1)

In [86]:
aa.sum(axis=0) #(2,3,4) 0번 숫자('2')를 가리면 (3,4) => 3차원에서 2차원으로 축소됨
               # 1초 안에 대답해야함

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [87]:
#Cobal and Fortran <- 

In [88]:
a.reshape(2,3,order='F')  스트라이드시 아래로 F V 

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.sum(axis)

In [89]:
a.reshape(2,3,order='C')  스트라이드 시 옆으로 C --> 

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 데이터 분석을 하건데, 대부분 pandas
# 월요일 부터는 이론적으로도 할것이다. 

In [ ]:
# 데이터 사이언스에서의 유니콘
# 유니콘 데이터

In [108]:
# 파일 형식
# 텍스트: human-readable / byte
# 여기 부터 with... 
# 파이썬은 무조건 텍스트로 들고 온다. 텍스트는 별다른 기능이 없다. 
# --> 간혹 객체를 저장하고 싶을 때는? 타입까지 저장하고 싶다면? : pickle??? #pickle# 개중요

In [114]:
%%writefile a.txt

UsageError: %%writefile is a cell magic, but the cell body is empty.


In [115]:
a = open('test.txt')

In [128]:
a.readline()  # next 부르는 것 과 같다.
              # 장점: 아무리 큰 파일도 한줄 씩 불러올 수 있다.
              # 단점: 메모리 공간 차지를 너무 많이 한다. 닫아주지 않으면. DB도 그렇다.
              # open과 close 사이의 공간을 context라고한다. 컨텍스트가 있는 상황에 쓰는 것이 with 이다. 

''

In [130]:
class D:
    def __enter__

In [131]:
d = D()

In [132]:
with d:
    pass

TypeError: 'D' object does not support the context manager protocol

In [133]:
#peak - Serialize, picle#
# peak????

In [146]:
a = [1,2,3]

In [147]:
import pickle
with open('b.txt','wb') as f:
    pickle.dump(a,f)

In [148]:
with open('b.txt','rb') as f:
    xx = pickle.load(f)  ## xx 이거 왜 접근 가능? 

In [ ]:
# 유니코드는 인코딩 디코딩이 필요하기 때문에 , 모든 것을 바이트 코드로 저장해야한다. 그런데 b'문근영' 에러

In [149]:
xx

[1, 2, 3]

In [ ]:
# 저장 꼭 해야한다. # pickle을 꼭 해야한다. # 울고 싶을 때가 많을 것이다. # 컴퓨터는 끄면 안된다.

In [ ]:
# 
np.loadtxt()  # 문자열로 저장되어 있지만, 넘파이 형태로 변환 시켜불러온다.

In [ ]:
np.save('c',c) # 어떤 파일에 배열을 저장하는데 allow_pickle=True가 기본이다. (객체를 저장해주는 것) 
# np.save('c.npy') 

In [ ]:
np.savez('z',z) # zip: 묶기, 압축 
               # mnist.npz 

In [ ]:
# 오래 보관할 때는, pickle
# 잠깐 보관할 때는, copy = 딥카피

In [151]:
# 모델학습 시킬 때 중간 중간 저장해 놓아야 한다. 이 때 피클을 사용한다 .
# 피클의 문제점: python 버전에 따라 달라진다

SyntaxError: invalid syntax (4199625348.py, line 1)

NameError: name 'rec' is not defined

NameError: name 'recarray' is not defined

In [154]:
np.core.records.array(a)

rec.array((1, 2, 3),
          dtype=[('f0', '<i8'), ('f1', '<i8'), ('f2', '<i8')])

In [155]:
a

[1, 2, 3]

In [156]:
a = np.arange(24).reshape((2,3,4))

In [157]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [158]:
namedtuple

<function collections.namedtuple(typename, field_names, *, rename=False, defaults=None, module=None)>

In [159]:
Point = namedtuple("Point", ['x','y'])

In [160]:
Point

__main__.Point

In [161]:
p = Point(3,4)

In [162]:
p

Point(x=3, y=4)

In [177]:
Point.x

_tuplegetter(0, 'Alias for field number 0')

In [178]:
parray = np.array([(1,2),(3,4),(5,6),(7,8)], dtype=[('x', '<i2'), ('y', '<f2')])

In [179]:
parray

array([(1, 2.), (3, 4.), (5, 6.), (7, 8.)],
      dtype=[('x', '<i2'), ('y', '<f2')])

In [185]:
parray.x

AttributeError: 'numpy.ndarray' object has no attribute 'x'

In [180]:
parray[-1]

(7, 8.)

In [181]:
recparray = np.core.records.array(parray)

In [184]:
recparray.x

array([1, 3, 5, 7], dtype=int16)

In [191]:
import numpy as np

recarray2 = np.core.records.array([
    (1, 'bolero', 'Maurice Ravel', "17:23", 200),
    (2, 'debussy', 'clair de lune', "5:03", 800),
    (3, 'chopin', 'nocturne op.9 no.2', "4:30", 200)
],
dtype=[('pk', 'i4'), ('composer', 'U100'), ('title', 'U100'), ('length', 'U50'), ('counts', 'i4')]
)

In [193]:
recarray2.composer

array(['bolero', 'debussy', 'chopin'], dtype='<U100')

In [197]:
i = np.identity(10)

In [198]:
i 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [199]:
a = np.arange(100).reshape((10,10))

In [200]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [202]:
b = np.ma.masked_array(a,i)

In [220]:
b

masked_array(
  data=[[--, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [10, --, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, --, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, --, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, --, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, --, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, --, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, --, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, --, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, --]],
  mask=[[ True, False, False, False, False, False, False, False, False,
         False],
        [False,  True, False, False, False, False, False, False, False,
         False],
        [False, False,  True, False, False, False, False, False, False,
         False],
        [False, False, False,  True, False, False, False, False, False,
         False],
        [False, False, False, False,  True, False, False, False, False,
         False],
        [False, False, False, False, False,  True

In [206]:
b.shape

(10, 10)

In [208]:
import inspect

In [218]:
b.data[2:9,1:8]

array([[21, 22, 23, 24, 25, 26, 27],
       [31, 32, 33, 34, 35, 36, 37],
       [41, 42, 43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55, 56, 57],
       [61, 62, 63, 64, 65, 66, 67],
       [71, 72, 73, 74, 75, 76, 77],
       [81, 82, 83, 84, 85, 86, 87]])