In [ ]:
import numpy as np

# numpy -> homo sequence vectorize

## numpy 벡터 만들기

In [ ]:
a = np.array((1,2,3,4))

In [ ]:
# 연습 공간
class A:
    def __array__(self):  # ufunc가 반환하는 객체, 
        return np.arange(6).reshape((2,3))

class B:
    def __array_function__(self,a,b,c,d):  # ufunc가 반환하는 객체, 
        return 'hello I am not array...'

aa = A()
bb = B()
arr_c = np.array(aa,order='C',copy=True)
# print('mro', getattr(arr_c, '__mro__'))
print(aa is arr_c) 
arr_f = np.array([],order='F',like=bb, copy=False) # 확인한 속성들: order, copy, like, ndmin, dtype
print(bb is arr_f) 

arr_c, arr_f

# 1 2 3
# 4 5 6
# In 'C' order, the array is stored in memory as 1 2 3 4 5 6, prioritizing row-wise storage.
# In 'F' order, the array is stored as 1 4 2 5 3 6, prioritizing column-wise storage.

In [ ]:
b = np.ndarray((1,4,3))

In [ ]:
# 연습공간
cc = np.ndarray((3,2,2,5), dtype='int32') # buffer, offset, strides 나중에..
cc

dd = np.ndarray((4,4), buffer=np.array([1,2,3,4,5,6,7,8,9,10,11]),
               offset=np.int_().itemsize*4,
               strides=(3,1),
               dtype='int32')

# dd,dd.cumprod(axis=0),dd.cumprod(axis=1),dd.cumsum(axis=0), dd.cumsum(axis=1)
# dd, dd.conj(), dd.conjugate()
import pickle

with open('./new_file.pickle','wb') as f:
    dd_tosave = dd.dump(f)
    # pickle.dump(dd_tosave, f)

with open('./new_file.pickle','rb') as f:
    data = pickle.load(f)
    print(data)

dd.flatten(), dd.getfield(dtype='int32'), dd.ravel(), dd.repeat([1,2,3])

## 벡터 모양 확인하기

In [ ]:
a.ndim, a.shape, a.dtype, a.size, a.data, a

In [ ]:
b.ndim, b.shape, b.dtype, b.size, b.data, b

## 넘파이의 복사 - 깊, 얕

In [ ]:
c = a
d = a.copy()
c is a,\
d is a

In [ ]:
e = b
f = b.copy()
e is b,\
f is b

## 넘파이는 기본이 뮤터블

In [ ]:
g = np.array([1,2,3,4])
g[3] = 5
g

In [ ]:
h = np.ndarray((2,3))
h[1,1] = 100
h

## 넘파이의 다차원 벡터는 메모리상에 연속적으로 저장된다!

## 넘파이의 다양한 다차원벡터들

In [ ]:
i = np.ones((3,4))
j = np.zeros((3,4))
i,j

In [ ]:
np.ones_like(i), np.zeros_like(j)

In [ ]:
np.identity(4), np.eye(4,3)

In [ ]:
np.triu((3,4,5,6)), np.tril((3,4,5,6))

## Numpy 의 연산

In [ ]:
qq = np.arange(24).reshape((4,6))
ww = np.arange(18).reshape(6,3)
vv = np.eye(6,3)

In [ ]:
ww, vv, ww+vv, ww-vv, # qq-ww, qq+ww

In [ ]:
qq * 4

In [ ]:
np.dot(qq,ww)

In [ ]:
qq, ww, qq@ww

## 넘파이의 브로드캐스팅

In [307]:
# 브로드캐스팅

# 1. 차원의 크기가 같아야 합니다: 두 배열의 차원 수가 다를 경우, 더 작은 차원의 배열의 형태(shape) 
#    앞에 1을 추가하여 차원 수를 맞춥니다.
# 2. 특정 차원에서 크기가 1인 경우, 브로드캐스팅이 가능합니다: 두 배열의 특정 차원의 크기가 같거나, 
#    한 배열에서 그 차원의 크기가 1일 때 브로드캐스팅이 가능합니다. 크기가 1인 차원은 다른 배열의 해당 차원 크기로 확장됩니다.

vv + 1, vv - 1, ww + [1,2,3], qq, qq+[[1,2],[3,3],[4,5],[1,2]]

# (4,6) <-브로드캐스팅- (1,1)
# (4,6) <-브로드캐스팅- (1,6)
# (4,6) <-브로드캐스팅- (4,1)
# (4,6) <-브로드캐스팅- (4.6) 
# (4,6) <-브로드캐스팅- (2,3) X
# (4,6) <-브로드캐스팅- (2,6) X

qq+[[1,2],[3,3],[4,5],[1,2]]


ValueError: operands could not be broadcast together with shapes (4,6) (4,2) 

## 넘파이 인덱싱, 슬라이싱

In [312]:
myndarr = np.arange(360).reshape(4,9,10)

In [313]:
myndarr

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [321]:
# 콤마 인덱싱
myndarr[:,4,-2],\
myndarr[1:3,4:7,1:3],\
myndarr[:,-2,:],\
myndarr[:,:,-2]

(array([ 48, 138, 228, 318]),
 array([[[131, 132],
         [141, 142],
         [151, 152]],
 
        [[221, 222],
         [231, 232],
         [241, 242]]]),
 array([[ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
        [250, 251, 252, 253, 254, 255, 256, 257, 258, 259],
        [340, 341, 342, 343, 344, 345, 346, 347, 348, 349]]),
 array([[  8,  18,  28,  38,  48,  58,  68,  78,  88],
        [ 98, 108, 118, 128, 138, 148, 158, 168, 178],
        [188, 198, 208, 218, 228, 238, 248, 258, 268],
        [278, 288, 298, 308, 318, 328, 338, 348, 358]]))

In [335]:
# 불린인덱싱: 불린으로 이루어진 행렬을 마스크로 사용하여, 필요한 값을 추출해 내는 방법이다. 
arr2d = np.arange(64).reshape((8,8))

In [338]:
arr2d
axis_ABC = np.array(['A','A','B','C','C','A','B','C'])
axis_ABC
arr2d, arr2d[axis_ABC == 'B']

(array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23],
        [48, 49, 50, 51, 52, 53, 54, 55]]))

In [356]:
len(arr2d), len(arr2d[0]), arr2d[3,4]

(8, 8, 28)

In [339]:
for i in range(len(arr2d)):
    for j in range(len(arr2d[i])):
        if j%2 == 0:
            arr2d[i, j]
            
            

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [ ]:
# 팬시인덱싱
# 