In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,])

In [3]:
b = a

In [4]:
b[0] = 100

In [5]:
a

array([100,   2,   3])

In [6]:
a = np.array([1,2,3,])

In [7]:
b = a.copy()

In [8]:
b[0] = 100

In [9]:
a

array([1, 2, 3])

In [14]:
x = [[1,2],[3,4]]

In [15]:
import copy

In [16]:
y = copy.deepcopy(x)

In [17]:
y[0][0] = 100

In [18]:
x

[[1, 2], [3, 4]]

In [11]:
y = x.copy() # y = x[:]

In [12]:
y[0][0] = 100

In [13]:
x # copy. deep, shallow

[[100, 2], [3, 4]]

In [19]:
xx = np.array([[1,2],[3,4]])

In [20]:
yy = xx.view()

In [21]:
yy[0,0] = 100

In [22]:
xx

array([[1, 2],
       [3, 4]])

In [24]:
xx[0,0]

1

In [25]:
a = np.arange(24).reshape(4,6)

In [40]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [42]:
a[[0,1,-1],[2,1,-3]]

array([ 2,  7, 21])

In [27]:
a[1][:]

array([ 6,  7,  8,  9, 10, 11])

In [28]:
a[1,:]

array([ 6,  7,  8,  9, 10, 11])

In [29]:
a[1]

array([ 6,  7,  8,  9, 10, 11])

In [31]:
a[[2,1]]

array([[12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11]])

In [32]:
import seaborn as sns

In [33]:
tips = sns.load_dataset('tips')

In [36]:
tips[['tip','total_bill']]

tip  total_bill
0    1.01       16.99
1    1.66       10.34
2    3.50       21.01
3    3.31       23.68
4    3.61       24.59
..    ...         ...
239  5.92       29.03
240  2.00       27.18
241  2.00       22.67
242  1.75       17.82
243  3.00       18.78

[244 rows x 2 columns]

In [45]:
aa = np.arange(24).reshape(2,3,4)

In [49]:
aa[:,1,:]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [50]:
aa[...,0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [44]:
a[None]

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [51]:
scipy > ndimage > scipy-toolkit
      > ml > scikit-learn

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 