In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a.shape

(3,)

In [4]:
a.dtype

dtype('int32')

In [8]:
class A:
    __x = 1 # mangling

In [10]:
A._A__x

1

In [6]:
dir(A)

['_A__x',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']

In [24]:
class B:
    def __get__(self, a,b):
        print('get')
        
    def __set__(self,x):
        print('set')
        return 1

class C:
    bb = B()
    def __init__(self):
        self.b = B()

In [25]:
C.bb

get


In [26]:
C.bb = 3

In [27]:
C.bb

3

In [28]:
dd = C()

In [29]:
dd.bb

3

In [35]:
class B:
    def __get__(self, a,b):
        print('get')
        
    def __set__(self,x, y):
        print('set')
        return 1

class C:
    bb = B()
    def __init__(self):
        self.b = B()

In [36]:
cc = C()

In [37]:
cc.bb

get


In [38]:
vars(cc)

{'b': <__main__.B at 0x1c4d380a940>}

In [39]:
cc.bb = 3

set


In [40]:
cc.bb

get


In [41]:
a = np.array([1,2,3,4])

In [46]:
vars(a)

TypeError: vars() argument must have __dict__ attribute

In [44]:
a.shape = (2,2)

In [45]:
a

array([[1, 2],
       [3, 4]])

In [47]:
import tensorflow as tf

In [48]:
x = tf.constant([1,2,3,4])

In [50]:
x.shape = (2,2)

AttributeError: can't set attribute

In [1]:
class D:
    def __init__(self):
        self.__x =0 
    def g(self):
        print('알려줌')
        return self.__x
    def s(self,t):
        print('set')
        self.__x = t
    x = property(g,s)

In [2]:
d = D()

In [3]:
d.x = 5

set


In [4]:
d.x

알려줌


5

In [77]:
d.x = 2

set


In [78]:
d.x

get


3

In [37]:
class E:
    def __init__(self, x):
        self.__xx = x
       
    @property
    def x(self):
        return self.__xx

In [38]:
d = E(3)

In [40]:
d.x

3

In [30]:
d.x = 5

set


In [42]:
import numpy as np

In [43]:
a = np.array([1,2,3,4])

In [45]:
a.ndim`

AttributeError: attribute 'ndim' of 'numpy.ndarray' objects is not writable

In [46]:
import seaborn as sns

In [47]:
tips = sns.load_dataset('tips')

In [48]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [49]:
a = np.zeros((3,4))

In [50]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
a = np.identity(4)

In [52]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
a = np.eye(3,4)

In [54]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [56]:
np.triu((3,4))

array([[3, 4],
       [0, 4]])

In [57]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [58]:
np.ones_like(a)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
import tensorflow as tf

In [60]:
tf.ones((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [61]:
np.lookfor('triangle')

Search results for 'triangle'
-----------------------------
numpy.tril
    Lower triangle of an array.
numpy.triu
    Upper triangle of an array.
numpy.hypot
    Given the "legs" of a right triangle, return its hypotenuse.
numpy.tril_indices
    Return the indices for the lower-triangle of an (n, m) array.
numpy.triu_indices
    Return the indices for the upper-triangle of an (n, m) array.
numpy.ma.hypot
    Given the "legs" of a right triangle, return its hypotenuse.
numpy.tril_indices_from
    Return the indices for the lower-triangle of arr.
numpy.triu_indices_from
    Return the indices for the upper-triangle of arr.
numpy.linalg._umath_linalg.eigh_lo
    eigh on the last two dimension and broadcast to the rest, using lower triangle
numpy.linalg._umath_linalg.eigh_up
    eigh on the last two dimension and broadcast to the rest, using upper triangle.
numpy.sin
    Trigonometric sine, element-wise.
numpy.tri
    An array with ones at and below the given diagonal and zeros elsewhere.


In [62]:
np.info('tril')

     *** Found in numpy ***
 tril(m, k=0)

Lower triangle of an array.

Return a copy of an array with elements above the `k`-th diagonal zeroed.

Parameters
----------
m : array_like, shape (M, N)
    Input array.
k : int, optional
    Diagonal above which to zero elements.  `k = 0` (the default) is the
    main diagonal, `k < 0` is below it and `k > 0` is above.

Returns
-------
tril : ndarray, shape (M, N)
    Lower triangle of `m`, of same shape and data-type as `m`.

See Also
--------
triu : same thing, only for the upper triangle

Examples
--------
>>> np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])
----------------------------------------------------------------------------

     *** Repeat reference found in numpy.lib *** 

     *** Repeat reference found in numpy.matlib *** 

     *** Repeat reference found in numpy.lib.twodim_base *** 

     *** Total of 4 references found. ***


In [63]:
a = 3

In [64]:
a

3

In [65]:
print(a)

3


In [73]:
class A:
    def __str__(self):
        print('str')
        return '1'
    def __repr__(self):
        print('repr')
        return '2'

In [74]:
x = A()

In [75]:
x

repr


2

In [76]:
print(x)

str
1


In [77]:
a = np.array([1,2,3,4])

In [78]:
a

array([1, 2, 3, 4])

In [79]:
print(a)

[1 2 3 4]


In [80]:
import inspect

In [ ]:
\n 예쁘게 표현 안해 줌

In [81]:
inspect.getsource(A)

TypeError: <class '__main__.A'> is a built-in class

In [86]:
a  = tf.constant([1,2,3])

In [87]:
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [88]:
print(a)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [89]:
import pprint

In [90]:
pprint.pprint(a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>


In [91]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [82]:
from sklearn.datasets import load_iris

In [83]:
data = load_iris()

In [85]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [96]:
a = np.array([1,2,3])
b = np.array([2,3,1])

In [100]:
aa = np.array([[1,2],[3,4]])
bb = np.array([[1,2],[3,4]])

In [103]:
aa, bb

(array([[1, 2],
        [3, 4]]),
 array([[1, 2],
        [3, 4]]))

In [104]:
aa.dot(bb)

array([[ 7, 10],
       [15, 22]])

In [ ]:
연산자 > 함수 or 메소드

In [97]:
np.dot(a,b)

11

In [98]:
a.dot(b)

11

In [99]:
a@b

11

In [ ]:
type __class__

# elementwise

In [94]:
a * b

array([1, 4, 9])

In [ ]:
class X:
    def __add__(se)

In [95]:
from operator import add

In [105]:
a 

array([1, 2, 3])

In [106]:
a + 1

array([2, 3, 4])

In [108]:
aa = np.array([[1,2],[3,4]])

In [109]:
aa

array([[1, 2],
       [3, 4]])

In [110]:
aa + 1

array([[2, 3],
       [4, 5]])

In [111]:
aa + np.array([[1,2]])

array([[2, 4],
       [4, 6]])

In [112]:
aa + np.array([[1],[2]])

array([[2, 3],
       [5, 6]])

In [113]:
aa + np.array([[1,2,3]])

ValueError: operands could not be broadcast together with shapes (2,2) (1,3) 

In [116]:
tf.constant([[1,2,3]]) + tf.constant([[1,2],[2,3]])

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [1,3] vs. [2,2] [Op:AddV2]

In [117]:
a = np.arange(24).reshape(4,6)

In [118]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [119]:
a[0][2]

2

In [138]:
b = np.array([1,2,3,4])

In [140]:
b > 2

array([False, False,  True,  True])

In [141]:
b[b>2]

array([3, 4])

In [132]:
comma indexing
boolean indexing

SyntaxError: invalid syntax (1117134382.py, line 1)

In [121]:
a = np.arange(24).reshape(2,3,4)

In [122]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [123]:
a[0][1][2]

6

In [124]:
a[0,1,2]

6

In [126]:
import seaborn as sns

In [127]:
tips = sns.load_dataset('tips')

In [130]:
tips.iloc[2,1] =100

In [143]:
tips[tips.tip > 3]

total_bill     tip     sex smoker  day    time  size
2         21.01  100.00    Male     No  Sun  Dinner     3
3         23.68    3.31    Male     No  Sun  Dinner     2
4         24.59    3.61  Female     No  Sun  Dinner     4
5         25.29    4.71    Male     No  Sun  Dinner     4
7         26.88    3.12    Male     No  Sun  Dinner     4
..          ...     ...     ...    ...  ...     ...   ...
219       30.14    3.09  Female    Yes  Sat  Dinner     4
221       13.42    3.48  Female    Yes  Fri   Lunch     2
232       11.61    3.39    Male     No  Sat  Dinner     2
238       35.83    4.67  Female     No  Sat  Dinner     3
239       29.03    5.92    Male     No  Sat  Dinner     3

[98 rows x 7 columns]