In [6]:
import numpy as np

In [31]:
a = np.arange(24)

In [32]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [35]:
a.resize((3,10), refcheck=False)

In [37]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23,  0,  0,  0,  0,  0,  0]])

In [40]:
b = a.flatten()

In [43]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  0,  0,  0,  0,  0,  0])

In [42]:
뷰 = 볼레로

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23,  0,  0,  0,  0,  0,  0]])

In [44]:
aa = np.arange(6).reshape(2,3)

In [45]:
aa

array([[0, 1, 2],
       [3, 4, 5]])

In [51]:
np.newaxis is None

True

In [46]:
aa[np.newaxis]    2,3 -> 1,2,3

array([[[0, 1, 2],
        [3, 4, 5]]])

In [47]:
aa[:,None]  2.1,3

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [49]:
aa[...,None]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [48]:
aa[:,:,None]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [14]:
b = a.res
hape((2,3,4))

In [16]:
np.reshape(a,(2,3,4))

array([[[100,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [12]:
b[0,0,0] = 100

In [13]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [9]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [1]:
import tensorflow as tf

In [4]:
from scipy import stats

In [5]:
stats.beta

['F_onewayBadInputSizesWarning',
 'F_onewayConstantInputWarning',
 'NumericalInverseHermite',
 'PearsonRConstantInputWarning',
 'PearsonRNearConstantInputWarning',
 'SpearmanRConstantInputWarning',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_binned_statistic',
 '_binomtest',
 '_boost',
 '_bootstrap',
 '_common',
 '_constants',
 '_continuous_distns',
 '_crosstab',
 '_discrete_distns',
 '_distn_infrastructure',
 '_distr_params',
 '_entropy',
 '_hypotests',
 '_ksstats',
 '_mannwhitneyu',
 '_multivariate',
 '_page_trend_test',
 '_qmc',
 '_qmc_cy',
 '_relative_risk',
 '_rvs_sampling',
 '_sobol',
 '_stats',
 '_stats_mstats_common',
 '_tukeylambda_stats',
 '_wilcoxon_data',
 'alexandergovern',
 'alpha',
 'anderson',
 'anderson_ksamp',
 'anglit',
 'ansari',
 'arcsine',
 'argus',
 'barnard_exact',
 'bartlett',
 'bayes_mvs',
 'bernoulli',
 'beta',
 'betabinom',
 'betaprime',
 'biasedurn',
 'binned_s

In [2]:
a = tf.constant([1,2,3,])

In [3]:
dir(a)

['OVERLOADABLE_OPERATORS',
 '_USE_EQUALITY',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__complex__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__tf_tracing_type__',
 '__true

In [52]:
from collections import namedtuple

In [53]:
a = namedtuple('Point', ['x','y'])

In [54]:
Point = namedtuple('Point', ['x','y'])

In [55]:
p1 = Point(x=3,y=4)

In [56]:
p1.x

3

In [57]:
p1[0]

3

In [58]:
import sys

In [59]:
sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

In [ ]:
reshape
- flatten / ravel
- [None]

In [60]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [62]:
x['name']

array(['Rex', 'Fido'], dtype='<U10')

In [64]:
xx = np.rec.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [67]:
xxx = np.ma.array([1,2,3],mask=[True, False, True])

In [69]:
xxx.count()

1

In [70]:
xxx = np.matrix([[1,2],[3,4]])

In [72]:
xxx = np.mat([[1,2],[3,4]])

In [74]:
xxx*xxx

matrix([[ 7, 10],
        [15, 22]])

In [71]:
xxx

matrix([[1, 2],
        [3, 4]])

In [66]:
xx.name

array(['Rex', 'Fido'], dtype='<U10')

In [75]:
from functools import reduce

In [77]:
reduce(lambda x,y:x+y, [1,2,3,4,5])

15

In [93]:
a = np.arange(6)

In [94]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [95]:
a.reshape(2,3, order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [85]:
aa = np.arange(24).reshape(2,3,4)

In [89]:
aa

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [92]:
aa.sum(axis=2)   # (2,3,4)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [ ]:
n -> 1
f
v 

In [84]:
a.sum(axis=1)

array([ 3, 12])

In [80]:
a.strides

(12, 4)

In [ ]:
파일 형식
- 


In [ ]:
파일 형식
- 텍스트 : human-readable / byte

In [96]:
%%writefile a.txt
1 2 3
4 5 6
6
7

Overwriting a.txt


In [125]:
a = open('a.txt')

In [126]:
dir(a)

['_CHUNK_SIZE',
 '__class__',
 '__del__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__next__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_checkClosed',
 '_checkReadable',
 '_checkSeekable',
 '_checkWritable',
 '_finalizing',
 'buffer',
 'close',
 'closed',
 'detach',
 'encoding',
 'errors',
 'fileno',
 'flush',
 'isatty',
 'line_buffering',
 'mode',
 'name',
 'newlines',
 'read',
 'readable',
 'readline',
 'readlines',
 'reconfigure',
 'seek',
 'seekable',
 'tell',
 'truncate',
 'writable',
 'write',
 'write_through',
 'writelines']

In [107]:
a.readline()

''

In [100]:
next(a)

'4 5 6\n'

In [108]:
a.close()

In [110]:
with a:
    pass

ValueError: I/O operation on closed file.

In [121]:
class D:
    def __enter__(self):
        print('enter')
    def __exit__(self, a,b,c):
        print('exit')

In [122]:
d = D()

In [124]:
with d:
    print('-----------')
    pass

enter
-----------
exit


In [127]:
import sqlite3

In [128]:
b = sqlite3.connect(':memory:')

In [129]:
with b:
    pass

['DataError',
 'DatabaseError',
 'Error',
 'IntegrityError',
 'InterfaceError',
 'InternalError',
 'NotSupportedError',
 'OperationalError',
 'ProgrammingError',
 'Warning',
 '__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'backup',
 'close',
 'commit',
 'create_aggregate',
 'create_collation',
 'create_function',
 'cursor',
 'enable_load_extension',
 'execute',
 'executemany',
 'executescript',
 'in_transaction',
 'interrupt',
 'isolation_level',
 'iterdump',
 'load_extension',
 'rollback',
 'row_factory',
 'set_authorizer',
 'set_progress_handler',
 'set_trace_callback',
 'text_factory',
 'total_changes']

In [130]:
a = [1,2,3]

In [132]:
import pickle # seriablizable

In [135]:
with open('b.txt', 'wb') as f:
    pickle.dump(a,f)

In [136]:
with open('b.txt', 'rb') as f:
    xx = pickle.load(f)

In [138]:
%%writefile c.txt
1 2 3
4 5 6

Writing c.txt


In [139]:
c = np.loadtxt('c.txt')

In [140]:
c

array([[1., 2., 3.],
       [4., 5., 6.]])

In [141]:
np.save('c.npy',c)

In [142]:
np.load('c.npy')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [143]:
import tensorflow as tf

In [144]:
import inspect

In [146]:
print(inspect.getsource(tf.keras.datasets.mnist.load_data))

@keras_export("keras.datasets.mnist.load_data")
def load_data(path="mnist.npz"):
    """Loads the MNIST dataset.

    This is a dataset of 60,000 28x28 grayscale images of the 10 digits,
    along with a test set of 10,000 images.
    More info can be found at the
    [MNIST homepage](http://yann.lecun.com/exdb/mnist/).

    Args:
      path: path where to cache the dataset locally
        (relative to `~/.keras/datasets`).

    Returns:
      Tuple of NumPy arrays: `(x_train, y_train), (x_test, y_test)`.

    **x_train**: uint8 NumPy array of grayscale image data with shapes
      `(60000, 28, 28)`, containing the training data. Pixel values range
      from 0 to 255.

    **y_train**: uint8 NumPy array of digit labels (integers in range 0-9)
      with shape `(60000,)` for the training data.

    **x_test**: uint8 NumPy array of grayscale image data with shapes
      (10000, 28, 28), containing the test data. Pixel values range
      from 0 to 255.

    **y_test**: uint8 NumPy array 

In [137]:
xx

[1, 2, 3]

In [134]:
b'문근영'

SyntaxError: bytes can only contain ASCII literal characters. (3430145453.py, line 1)